/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-04 03:50:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.onedaybaking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addClass_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write('\r');
      out.write('\n');

	String ids = (String) session.getAttribute("idKey");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<title>강의 등록</title>\r\n");
      out.write("	<link href=\"yeounsu.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("	<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<style>\r\n");
      out.write("		.step-section {\r\n");
      out.write("			display: none;\r\n");
      out.write("		}\r\n");
      out.write("		.step-section.active {\r\n");
      out.write("			display: block;\r\n");
      out.write("		}\r\n");
      out.write("		.detailcontainer {\r\n");
      out.write("			display: grid;\r\n");
      out.write("			grid-template-columns: repeat(2, 1fr); \r\n");
      out.write("			grid-gap: 10px; \r\n");
      out.write("			border: 1px solid #ccc;\r\n");
      out.write("			width: 700px;\r\n");
      out.write("			left: 100px;'\r\n");
      out.write("			border-color: #E7DBCC; \r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("		}\r\n");
      out.write("		.detailitem {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			margin-top: 15px;\r\n");
      out.write("			margin-bottom: 15px;\r\n");
      out.write("		}\r\n");
      out.write("		.button-container2 {\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("		}\r\n");
      out.write("		.custom-button {\r\n");
      out.write("			padding: 10px 70px;\r\n");
      out.write("			display: inline-block;\r\n");
      out.write("			margin: 0 auto;\r\n");
      out.write("			background-color: #884A01; \r\n");
      out.write("			color: white;\r\n");
      out.write("			border: 1px solid #884A01;\r\n");
      out.write("			border-radius: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"button-container\">\r\n");
      out.write("            <button id=\"btnPanel1\" class=\"btnpanel active\" onclick=\"showPanel('panel1', 'btnPanel1')\">강의 등록</button>\r\n");
      out.write("            <button id=\"btnPanel2\" class=\"btnpanel\" onclick=\"showPanel('panel2', 'btnPanel2')\">강사 등록</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"panel1\" class=\"panel-container active\">\r\n");
      out.write("			<div id=\"step1\" class=\"step-section active\">\r\n");
      out.write("    			<form id=\"step1Form\" onsubmit=\"return false;\">\r\n");
      out.write("    				<label for=\"title\" style=\"font-weight: bold; font-size: 14px;\">클래스 상세 내용</label><br><br>\r\n");
      out.write("					<label id=\"notice\" for=\"notice\" style=\"font-size: 14px\">클래스 상세 내용을 작성해주세요.</label><br><br>\r\n");
      out.write("					<label for=\"classnames\">클래스 명</label>\r\n");
      out.write("					<label id=\"must\">(필수)</label><br>\r\n");
      out.write("					<input type=\"text\" id=\"classnames\" name=\"typingname\" placeholder=\"클래스 명을 입력하세요\" style=\"color: gray; width: 100%\"><br><br><br>\r\n");
      out.write("					<label for=\"selectcate\">카테고리</label> <br>\r\n");
      out.write("					\r\n");
      out.write("					<select id= \"cate1\" onchange=\"categoryChange(this)\">\r\n");
      out.write("						<option>카테고리를 선택해주세요.</option>\r\n");
      out.write("						<option value=\"제과\">제과</option>\r\n");
      out.write("						<option value=\"제빵\">제빵</option>\r\n");
      out.write("						<option value=\"커피\">커피</option>\r\n");
      out.write("					</select>\r\n");
      out.write("					<select id=\"cate2\">\r\n");
      out.write("						<option>원하는 세부사항을 선택해주세요.</option>\r\n");
      out.write("					</select>\r\n");
      out.write("					<br><br><br><br>\r\n");
      out.write("					<label for=\"classtitleimg\">대표 이미지</label>\r\n");
      out.write("					<label id=\"must\">(필수)</label> <br>\r\n");
      out.write("\r\n");
      out.write("					<div id=\"image-upload-container\" style=\"position: relative; display: inline-block; width: 50%\">\r\n");
      out.write("					    <div id=\"image-frame\" style=\"width: 100%; height: 200px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("					     	<img id=\"uploaded-image\" src=\"photoadd.png\" style=\"max-width: 10%; max-height: 10%; \" ><br>\r\n");
      out.write("					        클릭하여 이미지를 업로드하세요\r\n");
      out.write("					    </div >\r\n");
      out.write("					    <input type=\"file\" id=\"image-upload\" style=\"position: absolute; width: 100%; height: 100%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div style=\"position: absolute; display: inline-block;\">\r\n");
      out.write("						<div id=\"image-upload-container2\" style=\"position: absolute; display: inline-block;\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<div id=\"image-frame2\" style=\"font-size:9px; width: 150px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("									<img id=\"uploaded-image2\" src=\"photoadd.png\" style=\"max-width: 20%; max-height: 20%; \" ><br>\r\n");
      out.write("									클릭하여 이미지를 업로드하세요\r\n");
      out.write("								</div>\r\n");
      out.write("								<input type=\"file\" id=\"image-upload2\" style=\"position: absolute; width: 100%; height: 50%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("								<div id=\"image-frame3\" style=\"font-size:9px; width: 150px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("									<img id=\"uploaded-image3\" src=\"photoadd.png\" style=\"max-width: 20%; max-height: 20%; \" ><br>\r\n");
      out.write("									클릭하여 이미지를 업로드하세요\r\n");
      out.write("								</div>\r\n");
      out.write("								<input type=\"file\" id=\"image-upload3\" style=\"position: absolute; width: 100%; height: 50%; top: 152; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"image-upload-container2\" style=\"position: absolute; display: inline-block;\">\r\n");
      out.write("							<div style=\"position: absolute; left: 151px;\">\r\n");
      out.write("    							<div id=\"image-frame4\" style=\" font-size:9px; width: 150px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("     								<img id=\"uploaded-image4\" src=\"photoadd.png\" style=\"max-width: 20%; max-height: 20%; \" ><br>\r\n");
      out.write("									클릭하여 이미지를 업로드하세요\r\n");
      out.write("								</div>\r\n");
      out.write("								<input type=\"file\" id=\"image-upload4\" style=\"position: absolute; width: 100%; height: 50%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("								<div id=\"image-frame5\" style=\" font-size:9px; width: 150px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("									<img id=\"uploaded-image5\" src=\"photoadd.png\" style=\"max-width: 20%; max-height: 20%; \" ><br>\r\n");
      out.write("									클릭하여 이미지를 업로드하세요\r\n");
      out.write("								</div>\r\n");
      out.write("								<input type=\"file\" id=\"image-upload5\" style=\"position: absolute; width: 100%; height: 50%; top: 152; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<script>\r\n");
      out.write("					    document.getElementById('image-frame').addEventListener('click', function() {\r\n");
      out.write("					        document.getElementById('image-upload').click();        \r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('image-frame2').addEventListener('click', function() {\r\n");
      out.write("					        document.getElementById('image-upload2').click();\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('image-frame3').addEventListener('click', function() {\r\n");
      out.write("					        document.getElementById('image-upload3').click();\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('image-frame4').addEventListener('click', function() {\r\n");
      out.write("					        document.getElementById('image-upload4').click();\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('image-frame5').addEventListener('click', function() {\r\n");
      out.write("					        document.getElementById('image-upload5').click();\r\n");
      out.write("					    });\r\n");
      out.write("					\r\n");
      out.write("					    document.getElementById('image-upload').addEventListener('change', function() {\r\n");
      out.write("					        var file = this.files[0];\r\n");
      out.write("					        if (file) {\r\n");
      out.write("					            var reader = new FileReader();\r\n");
      out.write("					            reader.onload = function(e) {\r\n");
      out.write("					                document.getElementById('image-frame').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("					            };\r\n");
      out.write("					            reader.readAsDataURL(file);\r\n");
      out.write("					        }\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('image-upload2').addEventListener('change', function() {\r\n");
      out.write("					        var file = this.files[0];\r\n");
      out.write("					        if (file) {\r\n");
      out.write("					            var reader = new FileReader();\r\n");
      out.write("					            reader.onload = function(e) {\r\n");
      out.write("					                document.getElementById('image-frame2').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("					            };\r\n");
      out.write("					            reader.readAsDataURL(file);\r\n");
      out.write("					        }\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('image-upload3').addEventListener('change', function() {\r\n");
      out.write("					        var file = this.files[0];\r\n");
      out.write("					        if (file) {\r\n");
      out.write("					            var reader = new FileReader();\r\n");
      out.write("					            reader.onload = function(e) {\r\n");
      out.write("					                document.getElementById('image-frame3').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("					            };\r\n");
      out.write("					            reader.readAsDataURL(file);\r\n");
      out.write("					        }\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('image-upload4').addEventListener('change', function() {\r\n");
      out.write("					        var file = this.files[0];\r\n");
      out.write("					        if (file) {\r\n");
      out.write("					            var reader = new FileReader();\r\n");
      out.write("					            reader.onload = function(e) {\r\n");
      out.write("					                document.getElementById('image-frame4').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("					            };\r\n");
      out.write("					            reader.readAsDataURL(file);\r\n");
      out.write("					        }\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('image-upload5').addEventListener('change', function() {\r\n");
      out.write("					        var file = this.files[0];\r\n");
      out.write("					        if (file) {\r\n");
      out.write("					            var reader = new FileReader();\r\n");
      out.write("					            reader.onload = function(e) {\r\n");
      out.write("					                document.getElementById('image-frame5').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("					            };\r\n");
      out.write("					            reader.readAsDataURL(file);\r\n");
      out.write("					        }\r\n");
      out.write("					    });\r\n");
      out.write("					</script>\r\n");
      out.write("					<br><br><br>\r\n");
      out.write("					<label for=\"classhard\">수업 난이도</label>\r\n");
      out.write("	<label id=\"must\">(필수)</label><br>\r\n");
      out.write("	<div class=\"btn-group\" role=\"group\" aria-label=\"Basic radio toggle button group\" style=\"width:100%\">\r\n");
      out.write("  	 	<input type=\"radio\" class=\"btn-check\" name=\"difficulty\" id=\"btnradio1\" value=\"초급\" autocomplete=\"off\" checked>\r\n");
      out.write("    	<label class=\"btn btn-outline-primary\" for=\"btnradio1\">초급</label>\r\n");
      out.write("    \r\n");
      out.write("    	<input type=\"radio\" class=\"btn-check\" name=\"difficulty\" id=\"btnradio2\" value=\"중급\" autocomplete=\"off\">\r\n");
      out.write("    	<label class=\"btn btn-outline-primary\" for=\"btnradio2\">중급</label>\r\n");
      out.write("    \r\n");
      out.write("    	<input type=\"radio\" class=\"btn-check\" name=\"difficulty\" id=\"btnradio3\" value=\"고급\" autocomplete=\"off\">\r\n");
      out.write("    	<label class=\"btn btn-outline-primary\" for=\"btnradio3\">고급</label>\r\n");
      out.write("	</div>\r\n");
      out.write("					<br><br><br>\r\n");
      out.write("					<label for=\"classfortime\">수업 소요시간</label>\r\n");
      out.write("					<label id=\"must\">(필수)</label><br>\r\n");
      out.write("					<input type=\"text\" id=\"classtimes\" name=\"classtime\" placeholder=\"30분 단위로 적어주세요 ex) 150\" style=\"color: gray; width: 100%\"><br><br><br><br><br>\r\n");
      out.write("   					<table>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td rowspan=\"2\"><label for=\"classfortime\">수업 소요시간</label>\r\n");
      out.write("								<label id=\"must\">(필수) &nbsp; &nbsp; &nbsp;</label> </td>\r\n");
      out.write("								<td colspan=\"2\" style=\"text-align: center;\" >최소 인원</td>\r\n");
      out.write("								<td style=\"text-align: center;\">최대 인원</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><input type=\"text\" id=\"minPerson\" name=\"minPerson\" placeholder=\"명\" style=\"color: gray; text-align: right;\"></td>\r\n");
      out.write("								<td>&nbsp;</td>\r\n");
      out.write("								<td><input type=\"text\" id=\"maxPerson\" name=\"maxPerson\" placeholder=\"명\" style=\"color: gray; text-align: right;\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("					<br><br><br>\r\n");
      out.write("					<label for=\"classfortime\">1인 수강금액</label>\r\n");
      out.write("					<label id=\"must\">(필수)</label><br>\r\n");
      out.write("					<input type=\"text\" id=\"price\" name=\"price\" placeholder=\"원\" style=\"color: gray;text-align: right; width: 100%\"><br><br><br><br><br><br>\r\n");
      out.write("			        <div class=\"button-container2\">\r\n");
      out.write("			        	<button class=\"custom-button\" onclick=\"nextStep(1)\">다음</button>\r\n");
      out.write("	        		</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- step 2 -->\r\n");
      out.write("			<div class=\"step-section\" id=\"step2\">\r\n");
      out.write("				<form id=\"step2Form\" onsubmit=\"return false;\">\r\n");
      out.write("					<label for=\"title\" style=\"font-weight: bold; font-size: 14px;\">클래스 상세 내용</label><br><br>\r\n");
      out.write("					<label id=\"notice\" for=\"notice\" style=\"font-size: 14px\">클래스 상세 내용에 들어갈 이미지를 등록해주세요.</label><br><br><br><br>\r\n");
      out.write("					<label for=\"classtitleimg\" style=\"position: relative; left: 60px;\">클래스 상세 내용 이미지</label>\r\n");
      out.write("					<label id=\"must\" style=\"position: relative; left: 60px;\" >(필수)</label> <br>\r\n");
      out.write("		\r\n");
      out.write("					<div id=\"image-upload-container3\" style=\"position: relative; display: inline-block; left: 60px;\"> <br>\r\n");
      out.write("						<div id=\"image-frame6\" style=\"width: 500px; height: 350px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("							<img id=\"uploaded-image6\" src=\"photoadd.png\" style=\"max-width: 10%; max-height: 10%; \" >\r\n");
      out.write("							<br>클릭하여 이미지를 업로드하세요\r\n");
      out.write("						</div>\r\n");
      out.write("						<input type=\"file\" id=\"image-upload6\" style=\"position: absolute; width: 100%; height: 100%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("					</div>\r\n");
      out.write("					<script>\r\n");
      out.write("						document.getElementById('image-frame6').addEventListener('click', function() {\r\n");
      out.write("						        document.getElementById('image-upload6').click();        \r\n");
      out.write("						    });\r\n");
      out.write("						    \r\n");
      out.write("						document.getElementById('image-upload6').addEventListener('change', function() {\r\n");
      out.write("						    var file = this.files[0];\r\n");
      out.write("						    if (file) {\r\n");
      out.write("						        var reader = new FileReader();\r\n");
      out.write("						        reader.onload = function(e) {\r\n");
      out.write("						            document.getElementById('image-frame6').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("						        };\r\n");
      out.write("						        reader.readAsDataURL(file);\r\n");
      out.write("						    }\r\n");
      out.write("						});\r\n");
      out.write("					</script>\r\n");
      out.write("					<label for=\"classdetailtitleimg\" style=\"position: relative; left: 60px; font-size: 10px; color: gray;\"> 이미지 사이즈는 ?:?% 이에요. (넓이 사이즈가 맞지 않으면 이미지가 잘리거나 뭉개질 수 있어요.) </label><br><br><br>\r\n");
      out.write("					<div class=\"button-container2\">\r\n");
      out.write("						<button class=\"custom-button\" onclick=\"previousStep(2)\">이전</button>\r\n");
      out.write("						<button class=\"custom-button\" onclick=\"nextStep(2)\">다음</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- step 3 -->\r\n");
      out.write("			<div class=\"step-section\" id=\"step3\">\r\n");
      out.write("    			<form id=\"step3Form\" onsubmit=\"return false;\">\r\n");
      out.write("					<label for=\"title\" style=\"font-weight: bold; font-size: 14px;\">공간정보</label><br><br>\r\n");
      out.write("    				<label id=\"notice\" for=\"notice\" style=\"font-size: 14px\">클래스 공간을 소개해주세요.</label><br><br><br>\r\n");
      out.write("					<label for=\"classtitleimg\" style=\"position: relative; \">공간 사진</label>\r\n");
      out.write("					<label id=\"must\" style=\"position: relative; \" >(필수)</label> <br>\r\n");
      out.write("					<div id=\"image-upload-container8\" style=\"position: relative; display: inline-block; left:30px; \"> <br>\r\n");
      out.write("    					<div id=\"image-frame8\" style=\"width: 300px; height: 200px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("							<img id=\"uploaded-image8\" src=\"photoadd.png\" style=\"max-width: 10%; max-height: 10%; \" >\r\n");
      out.write("	     					프로필<br>\r\n");
      out.write("    					</div>\r\n");
      out.write("    					<input type=\"file\" id=\"image-upload8\" style=\"position: absolute; width: 100%; height: 100%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("					</div>\r\n");
      out.write("					<script>\r\n");
      out.write("						document.getElementById('image-frame8').addEventListener('click', function() {\r\n");
      out.write("						        document.getElementById('image-upload8').click();        \r\n");
      out.write("						    });\r\n");
      out.write("						    \r\n");
      out.write("						document.getElementById('image-upload8').addEventListener('change', function() {\r\n");
      out.write("						    var file = this.files[0];\r\n");
      out.write("						    if (file) {\r\n");
      out.write("						        var reader = new FileReader();\r\n");
      out.write("						        reader.onload = function(e) {\r\n");
      out.write("						            document.getElementById('image-frame8').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("						        };\r\n");
      out.write("						        reader.readAsDataURL(file);\r\n");
      out.write("						    }\r\n");
      out.write("						});\r\n");
      out.write("					</script>\r\n");
      out.write("					<div id=\"image-upload-container9\" style=\"position: relative; display: inline-block; left:30px; \"> <br>\r\n");
      out.write("					    <div id=\"image-frame9\" style=\"width: 300px; height: 200px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("						    <img id=\"uploaded-image9\" src=\"photoadd.png\" style=\"max-width: 10%; max-height: 10%; \" >\r\n");
      out.write("						    프로필<br>\r\n");
      out.write("					    </div >\r\n");
      out.write("					    <input type=\"file\" id=\"image-upload9\" style=\"position: absolute; width: 100%; height: 100%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("					</div>\r\n");
      out.write("					<script>\r\n");
      out.write("						document.getElementById('image-frame9').addEventListener('click', function() {\r\n");
      out.write("						        document.getElementById('image-upload9').click();        \r\n");
      out.write("						    });\r\n");
      out.write("						    \r\n");
      out.write("						document.getElementById('image-upload9').addEventListener('change', function() {\r\n");
      out.write("						    var file = this.files[0];\r\n");
      out.write("						    if (file) {\r\n");
      out.write("						        var reader = new FileReader();\r\n");
      out.write("						        reader.onload = function(e) {\r\n");
      out.write("						            document.getElementById('image-frame9').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("						        };\r\n");
      out.write("						        reader.readAsDataURL(file);\r\n");
      out.write("						    }\r\n");
      out.write("						});\r\n");
      out.write("					</script>\r\n");
      out.write("					<br><br>\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"text\" id=\"sample5_address\" placeholder=\"주소\" style=\"width:600px;\">\r\n");
      out.write("						<input type=\"text\" id=\"addressdetails\" placeholder=\"자세한 주소를 입력해주세요.\" style=\"width:400px;\">\r\n");
      out.write("						<input type=\"button\" onclick=\"sample5_execDaumPostcode()\" value=\"주소 검색\"><br>\r\n");
      out.write("						<div id=\"map\" style=\"width:500px;height:400px;margin-top:10px;display:none\"></div>\r\n");
      out.write("						<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("						<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("						<script>					\r\n");
      out.write("						    var mapContainer = document.getElementById('map'), // 지도를 표시할 div\r\n");
      out.write("						        mapOption = {\r\n");
      out.write("						            center: new daum.maps.LatLng(37.537187, 127.005476), // 지도의 중심좌표\r\n");
      out.write("						            level: 5 // 지도의 확대 레벨\r\n");
      out.write("						        };\r\n");
      out.write("						\r\n");
      out.write("						    //지도를 미리 생성\r\n");
      out.write("						    var map = new daum.maps.Map(mapContainer, mapOption);\r\n");
      out.write("						    //주소-좌표 변환 객체를 생성\r\n");
      out.write("						    var geocoder = new daum.maps.services.Geocoder();\r\n");
      out.write("						    //마커를 미리 생성\r\n");
      out.write("						    var marker = new daum.maps.Marker({\r\n");
      out.write("						        position: new daum.maps.LatLng(37.537187, 127.005476),\r\n");
      out.write("						        map: map\r\n");
      out.write("						    });\r\n");
      out.write("						\r\n");
      out.write("						    \r\n");
      out.write("						    function sample5_execDaumPostcode() {\r\n");
      out.write("						        new daum.Postcode({\r\n");
      out.write("						            oncomplete: function(data) {\r\n");
      out.write("						                var addr = data.address; // 최종 주소 변수\r\n");
      out.write("						\r\n");
      out.write("						                // 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("						                document.getElementById(\"sample5_address\").value = addr;\r\n");
      out.write("						                // 주소로 상세 정보를 검색\r\n");
      out.write("						                geocoder.addressSearch(data.address, function(results, status) {\r\n");
      out.write("						                    // 정상적으로 검색이 완료됐으면\r\n");
      out.write("						                    if (status === daum.maps.services.Status.OK) {\r\n");
      out.write("						\r\n");
      out.write("						                        var result = results[0]; //첫번째 결과의 값을 활용\r\n");
      out.write("						\r\n");
      out.write("						                        // 해당 주소에 대한 좌표를 받아서\r\n");
      out.write("						                        var coords = new daum.maps.LatLng(result.y, result.x);\r\n");
      out.write("						                        // 지도를 보여준다.\r\n");
      out.write("						                        mapContainer.style.display = \"block\";\r\n");
      out.write("						                        map.relayout();\r\n");
      out.write("						                        // 지도 중심을 변경한다.\r\n");
      out.write("						                        map.setCenter(coords);\r\n");
      out.write("						                        // 마커를 결과값으로 받은 위치로 옮긴다.\r\n");
      out.write("						                        marker.setPosition(coords)\r\n");
      out.write("						                    }\r\n");
      out.write("						                });\r\n");
      out.write("						            }\r\n");
      out.write("						        }).open();\r\n");
      out.write("						    }\r\n");
      out.write("						</script>\r\n");
      out.write("					</div>\r\n");
      out.write("					<br><br>\r\n");
      out.write("					<div>\r\n");
      out.write("						<label for=\"classtitleimg\" style=\"position: relative; font-weight: bold; font-size: 14px;\">제공 및 유의사항</label> <br><br>\r\n");
      out.write("						<div class=\"detailcontainer\">\r\n");
      out.write("							<!-- 1행 -->\r\n");
      out.write("							<div class=\"detailitem\">\r\n");
      out.write("							    <input type=\"checkbox\" id=\"checkbox1\" name=\"checkboxGroup\" style=\"width: 50px\">\r\n");
      out.write("							    <label for=\"checkbox1\">와이파이를 제공해요</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"detailitem\">\r\n");
      out.write("							    <input type=\"checkbox\" id=\"checkbox2\" name=\"checkboxGroup\" style=\"width: 50px\">\r\n");
      out.write("							    <label for=\"checkbox2\">포토존이 있어요</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 2행 -->\r\n");
      out.write("							<div class=\"detailitem\">\r\n");
      out.write("							    <input type=\"checkbox\" id=\"checkbox3\" name=\"checkboxGroup\" style=\"width: 50px\">\r\n");
      out.write("							    <label for=\"checkbox3\">주차공간이 있어요</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"detailitem\">\r\n");
      out.write("							    <input type=\"checkbox\" id=\"checkbox4\" name=\"checkboxGroup\" style=\"width: 50px\">\r\n");
      out.write("							    <label for=\"checkbox4\">반려동물 동반이 가능해요</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 3행 -->\r\n");
      out.write("							<div class=\"detailitem\">\r\n");
      out.write("							    <input type=\"checkbox\" id=\"checkbox5\" name=\"checkboxGroup\" style=\"width: 50px\">\r\n");
      out.write("							    <label for=\"checkbox5\">간단한 음료 및 다과를 제공해요</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"detailitem\">\r\n");
      out.write("							    <input type=\"checkbox\" id=\"checkbox6\" name=\"checkboxGroup\" style=\"width: 50px\">\r\n");
      out.write("							    <label for=\"checkbox6\">앞치마 및 장갑을 제공해요</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 4행 -->\r\n");
      out.write("							<div class=\"detailitem\">\r\n");
      out.write("								<input type=\"checkbox\" id=\"checkbox7\" name=\"checkboxGroup\" style=\"width: 50px\">\r\n");
      out.write("								<label for=\"checkbox7\">포장 용기를 제공해요</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<br><br>\r\n");
      out.write("						<label for=\"classtitleimg\" style=\"position: relative; font-weight: bold; font-size: 14px;\">건강 및 유의 사항</label> <br><br>\r\n");
      out.write("						<div class=\"detailcontainer\">\r\n");
      out.write("							<!-- 1행 -->\r\n");
      out.write("							<div class=\"detailitem\">\r\n");
      out.write("								<input type=\"checkbox\" id=\"checkbox8\" name=\"checkboxGroup\" style=\"width: 50px\">\r\n");
      out.write("								<label for=\"checkbox8\">손세정제가 비치 되어있어요</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"detailitem\">\r\n");
      out.write("								<input type=\"checkbox\" id=\"checkbox9\" name=\"checkboxGroup\" style=\"width: 50px\">\r\n");
      out.write("								<label for=\"checkbox9\">아이 동반은 추천하지 않아요</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 2행 -->\r\n");
      out.write("							<div class=\"detailitem\">\r\n");
      out.write("								<input type=\"checkbox\" id=\"checkbox10\" name=\"checkboxGroup\" style=\"width: 50px\">\r\n");
      out.write("								<label for=\"checkbox10\">실내 소독을 해요</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"detailitem\">\r\n");
      out.write("								<input type=\"checkbox\" id=\"checkbox11\" name=\"checkboxGroup\" style=\"width: 50px\">\r\n");
      out.write("								<label for=\"checkbox11\">날카로운 도구들을 많이 사용해요</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 3행 -->\r\n");
      out.write("							<div class=\"detailitem\">\r\n");
      out.write("								<input type=\"checkbox\" id=\"checkbox12\" name=\"checkboxGroup\" style=\"width: 50px\">\r\n");
      out.write("								<label for=\"checkbox12\">거리두기를 준수해요</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<br><br>\r\n");
      out.write("					<div class=\"button-container2\">\r\n");
      out.write("						<button class=\"custom-button\" onclick=\"previousStep(3)\">이전</button>\r\n");
      out.write("						<button class=\"custom-button\" onclick=\"nextStep(3)\">다음</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div><!-- panel1 div -->\r\n");
      out.write("		\r\n");
      out.write("        <!-- 강사 등록하기 패널에 해당 jsp 파일 추가한 것. 이후 수정 필요 -->\r\n");
      out.write("		<div id=\"panel2\" class=\"panel-container\">\r\n");
      out.write("			<label for=\"title\" style=\"font-weight: bold; font-size: 14px;\">강사 소개</label><br>\r\n");
      out.write("			<br>\r\n");
      out.write("			<label id=\"notice\" for=\"notice\" style=\"font-size: 14px\">해당 클래스의 강사님을 소개해주세요.</label><br>\r\n");
      out.write("			<br><br>\r\n");
      out.write("			<label for=\"classtitleimg\" style=\"position: relative; \">강사 사진</label>\r\n");
      out.write("			<label id=\"must\" style=\"position: relative; \" >(필수)</label> <br>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"image-upload-container4\" style=\"position: relative; display: inline-block; left:30px; \"> <br>\r\n");
      out.write("				<div id=\"image-frame7\" style=\"width: 100px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("					<img id=\"uploaded-image7\" src=\"photoadd.png\" style=\"max-width: 30%; max-height: 30%; \" >\r\n");
      out.write("					프로필<br>\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<input type=\"file\" id=\"image-upload7\" style=\"position: absolute; width: 100%; height: 100%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("			</div>\r\n");
      out.write("			<script>\r\n");
      out.write("				document.getElementById('image-frame7').addEventListener('click', function() {\r\n");
      out.write("				        document.getElementById('image-upload7').click();        \r\n");
      out.write("				    });\r\n");
      out.write("				    \r\n");
      out.write("				document.getElementById('image-upload7').addEventListener('change', function() {\r\n");
      out.write("				    var file = this.files[0];\r\n");
      out.write("				    if (file) {\r\n");
      out.write("				        var reader = new FileReader();\r\n");
      out.write("				        reader.onload = function(e) {\r\n");
      out.write("				            document.getElementById('image-frame7').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("				        };\r\n");
      out.write("				        reader.readAsDataURL(file);\r\n");
      out.write("				    }\r\n");
      out.write("				});\r\n");
      out.write("			</script>\r\n");
      out.write("\r\n");
      out.write("			<br><br>\r\n");
      out.write("			<label for=\"classforteacher\">상호명 또는 닉네임</label> \r\n");
      out.write("			<input type=\"text\" id=\"shopname\" name=\"username\" placeholder=\"상호명 또는 닉네임을 입력해 주세요.\" style=\"color: gray;\"><br><br>\r\n");
      out.write("			<br><br>\r\n");
      out.write("			<label for=\"classintroduce\">강사님 소개</label>\r\n");
      out.write("   			<label id=\"must\">(필수)</label> <br>\r\n");
      out.write("			<input type=\"text\" id=\"teacherintro\" name=\"typingintro\" placeholder=\"강사 소개를 입력해 주세요.\" style=\"color: gray; height: 300px;\"><br><br>\r\n");
      out.write("     		<br><br><br>\r\n");
      out.write("			<div class=\"button-container2\">\r\n");
      out.write("				<button type=\"button\" class=\"custom-button\" onclick=\"previousStep(4)\">이전</button>\r\n");
      out.write("				<button class=\"custom-button\" type=\"button\"	 onclick=\"test()\">저장하기</button>\r\n");
      out.write("			<form name=\"addClassFrm\" method=\"post\" action=\"addClass\" enctype=\"multipart/form-data\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classname\" name=\"classname\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classteacherinfo\" name=\"classteacherinfo\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"offercontent\" name=\"offercontent\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"categorygroup\" name=\"categorygroup\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"categoryname\" name=\"categoryname\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classtime\" name=\"classtime\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"address\" name=\"address\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"addressdetail\" name=\"addressdetail\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classlevel\" name=\"classlevel\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classimg1\" name =\"classimg1\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classimg2\" name =\"classimg2\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classimg3\" name =\"classimg3\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classimg4\" name =\"classimg4\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classimg5\" name =\"classimg5\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classcontent\" name =\"classcontent\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classteacherimg\" name =\"classteacherimg\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"roomimg1\" name =\"roomimg1\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"rommimg2\" name =\"rommimg2\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classstatus\" name =\"classstatus\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classmin\" name =\"classmin\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classmax\" name =\"classmax\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"classprice\" name =\"classprice\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"ids\" name=\"ids\" value=\"");
      out.print(ids);
      out.write("\">\r\n");
      out.write("				<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <span class=\"close\" onclick=\"closeModal()\">&times;</span>\r\n");
      out.write("    <p>저장되었습니다!</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    function categoryChange(e) {\r\n");
      out.write("        var cate2_a = [\"케이크\", \"파이\", \"마카롱\", \"쿠키\",\"머핀\",\"버터 바\",\"팬케이크\",\"와플\",\"기타\"];\r\n");
      out.write("        var cate2_b = [\"크로와상\", \"베이글\", \"식빵\", \"바게트\",\"호밀빵\",\"호떡\",\"롤케이크\",\"기타\"];\r\n");
      out.write("        var cate2_c = [\"에스프레소\", \"아메리카노\", \"카페라떼\", \"카푸치노\", \"모카\",\"아이스 커피\",\"라떼\",\"마끼야또\",\"콜드 브루\",\"더치 커피\",\"기타\"];\r\n");
      out.write("        var cate2_d = document.getElementById(\"cate2\");\r\n");
      out.write("\r\n");
      out.write("        var target = cate2_d; // 수정: target 변수 정의\r\n");
      out.write("\r\n");
      out.write("        if(e.value == \"제과\") var d = cate2_a;\r\n");
      out.write("        else if(e.value == \"제빵\") var d = cate2_b;\r\n");
      out.write("        else if(e.value == \"커피\") var d = cate2_c;\r\n");
      out.write("\r\n");
      out.write("        target.options.length = 0;\r\n");
      out.write("\r\n");
      out.write("        for (var x in d) {\r\n");
      out.write("           var opt = document.createElement(\"option\");\r\n");
      out.write("           opt.value = d[x];\r\n");
      out.write("           opt.innerHTML = d[x];\r\n");
      out.write("           target.appendChild(opt);\r\n");
      out.write("        } \r\n");
      out.write("    }\r\n");
      out.write("		function showPanel(panelId, buttonId) {\r\n");
      out.write("			var panels = document.querySelectorAll('.panel-container');\r\n");
      out.write("			panels.forEach(function(panel) {\r\n");
      out.write("			    panel.classList.remove('active');\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			var buttons = document.querySelectorAll('.button-container button');\r\n");
      out.write("			buttons.forEach(function(button) {\r\n");
      out.write("			    button.classList.remove('active');\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			var currentPanel = document.getElementById(panelId);\r\n");
      out.write("			currentPanel.classList.add('active');\r\n");
      out.write("			\r\n");
      out.write("			var currentButton = document.getElementById(buttonId);\r\n");
      out.write("			currentButton.classList.add('active');\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function nextStep(currentStep) {\r\n");
      out.write("			if (currentStep >= 3) {\r\n");
      out.write("				showPanel('panel2', 'btnPanel2');\r\n");
      out.write("				currentStep--;\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			document.getElementById('step' + currentStep).classList.remove('active');\r\n");
      out.write("			document.getElementById('step' + (currentStep + 1)).classList.add('active');\r\n");
      out.write("		}\r\n");
      out.write("	    \r\n");
      out.write("		function previousStep(currentStep) {\r\n");
      out.write("\r\n");
      out.write("			if (currentStep >= 4) {\r\n");
      out.write("				showPanel('panel1', 'btnPanel1');\r\n");
      out.write("				currentStep--;\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			document.getElementById('step' + currentStep).classList.remove('active');\r\n");
      out.write("			document.getElementById('step' + (currentStep - 1)).classList.add('active');\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		function test() {\r\n");
      out.write("			var h1 = document.getElementById(\"classnames\").value;\r\n");
      out.write("	        var a1 = document.getElementById(\"teacherintro\").value;\r\n");
      out.write("	        var b1 = document.getElementById(\"shopname\").value;\r\n");
      out.write("	        var c1 = document.getElementById(\"cate1\").value;\r\n");
      out.write("	        var d1 = document.getElementById(\"cate2\").value;\r\n");
      out.write("	        var e1 = document.getElementById(\"classtimes\").value;\r\n");
      out.write("	        var selectedDifficulty = document.querySelector('input[name=\"difficulty\"]:checked').value;\r\n");
      out.write("	        var f1 = document.getElementById(\"minPerson\").value;\r\n");
      out.write("	        var f2 = document.getElementById(\"maxPerson\").value;\r\n");
      out.write("	        var g1 = document.getElementById(\"price\").value;\r\n");
      out.write("	        var i1 = document.getElementById(\"sample5_address\").value;\r\n");
      out.write("	        var i2 = document.getElementById(\"addressdetails\").value;\r\n");
      out.write("	        var imageFile = document.getElementById(\"image-upload\").files[0];\r\n");
      out.write("	        var imageFile2 = document.getElementById(\"image-upload2\").files[0];\r\n");
      out.write("	        var imageFile3 = document.getElementById(\"image-upload3\").files[0];\r\n");
      out.write("	        var imageFile4 = document.getElementById(\"image-upload4\").files[0];\r\n");
      out.write("	        var imageFile5 = document.getElementById(\"image-upload5\").files[0];\r\n");
      out.write("	        var imageFile6 = document.getElementById(\"image-upload6\").files[0];\r\n");
      out.write("	        var imageFile7 = document.getElementById(\"image-upload7\").files[0];\r\n");
      out.write("	        var imageFile8 = document.getElementById(\"image-upload8\").files[0];\r\n");
      out.write("	        var imageFile9 = document.getElementById(\"image-upload9\").files[0];\r\n");
      out.write("	        ///////////////////////////////////////////////////\r\n");
      out.write("	        var checkboxes = document.querySelectorAll('input[name=\"checkboxGroup\"]');\r\n");
      out.write("	        var checkedItems = [];\r\n");
      out.write("	        var lists = [\"와이파이를 제공해요\", \"포토존이 있어요\", \"주차공간이 있어요\", \"반려동물 동반이 가능해요\", \"간단한 음료 및 다과를 제공해요\", \"앞치마 및 장갑을 제공해요\", \"포장 용기를 제공해요\", \"손세정제가 비치 되어있어요\", \"아이 동반은 추천하지 않아요\", \"실내 소독을 해요\", \"날카로운 도구들을 많이 사용해요\", \"거리두기를 준수해요\"];\r\n");
      out.write("			var a = 0;\r\n");
      out.write("			\r\n");
      out.write("	        checkboxes.forEach(function(checkbox) {\r\n");
      out.write("	            if (checkbox.checked) {\r\n");
      out.write("	                checkedItems.push(lists[a]);\r\n");
      out.write("	            } else {\r\n");
      out.write("	                checkedItems.push(0);\r\n");
      out.write("	            }\r\n");
      out.write("	            a++;\r\n");
      out.write("	        });\r\n");
      out.write("	        ////////////////////////////////////////////////\r\n");
      out.write("	        \r\n");
      out.write("	        if (imageFile != null) {\r\n");
      out.write("		        var imageName = imageFile.name;\r\n");
      out.write("		        var reader = new FileReader();\r\n");
      out.write("		        reader.onload = function(e) {\r\n");
      out.write("					reader.readAsDataURL(imageFile);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"classimg1\").value = imageName;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile2 != null) {\r\n");
      out.write("		        var imageName2 = imageFile2.name;\r\n");
      out.write("		        var reader2 = new FileReader();\r\n");
      out.write("		        reader2.onload = function(e) {\r\n");
      out.write("					reader2.readAsDataURL(imageFile2);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"classimg2\").value = imageName2;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile3 != null) {\r\n");
      out.write("		        var imageName3 = imageFile3.name;\r\n");
      out.write("		        var reader3 = new FileReader();\r\n");
      out.write("		        reader3.onload = function(e) {\r\n");
      out.write("					reader3.readAsDataURL(imageFile2);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"classimg3\").value = imageName3;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile4 != null) {\r\n");
      out.write("		        var imageName4 = imageFile4.name;\r\n");
      out.write("		        var reader4 = new FileReader();\r\n");
      out.write("		        reader4.onload = function(e) {\r\n");
      out.write("					reader4.readAsDataURL(imageFile4);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"classimg4\").value = imageName4;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile5 != null) {\r\n");
      out.write("		        var imageName5 = imageFile5.name;\r\n");
      out.write("		        var reader5 = new FileReader();\r\n");
      out.write("		        reader5.onload = function(e) {\r\n");
      out.write("					reader5.readAsDataURL(imageFile5);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"classimg5\").value = imageName5;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile6 != null) {\r\n");
      out.write("		        var imageName6 = imageFile6.name;\r\n");
      out.write("		        var reader6 = new FileReader();\r\n");
      out.write("		        reader6.onload = function(e) {\r\n");
      out.write("					reader6.readAsDataURL(imageFile6);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"classcontent\").value = imageName6;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile7 != null) {\r\n");
      out.write("		        var imageName7 = imageFile7.name;\r\n");
      out.write("		        var reader7 = new FileReader();\r\n");
      out.write("		        reader7.onload = function(e) {\r\n");
      out.write("					reader7.readAsDataURL(imageFile7);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"classteacherimg\").value = imageName7;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile8 != null) {\r\n");
      out.write("		        var imageName8 = imageFile8.name;\r\n");
      out.write("		        var reader8 = new FileReader();\r\n");
      out.write("		        reader8.onload = function(e) {\r\n");
      out.write("					reader8.readAsDataURL(imageFile8);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"roomimg1\").value = imageName8;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile9 != null) {\r\n");
      out.write("		        var imageName9 = imageFile9.name;\r\n");
      out.write("		        var reader9 = new FileReader();\r\n");
      out.write("		        reader9.onload = function(e) {\r\n");
      out.write("					reader9.readAsDataURL(imageFile9);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"rommimg2\").value = imageName9;\r\n");
      out.write("	        }\r\n");
      out.write("	        \r\n");
      out.write("	        \r\n");
      out.write("	        document.getElementById(\"classname\").value = h1;\r\n");
      out.write("	        document.getElementById(\"classteacherinfo\").value = a1;\r\n");
      out.write("	        document.getElementById(\"offercontent\").value = b1;\r\n");
      out.write("	        document.getElementById(\"categorygroup\").value = c1;\r\n");
      out.write("	        document.getElementById(\"categoryname\").value = d1;\r\n");
      out.write("	        document.getElementById(\"classtime\").value = e1;\r\n");
      out.write("	        document.getElementById(\"address\").value = i1;\r\n");
      out.write("	        document.getElementById(\"addressdetail\").value = i2;\r\n");
      out.write("	        document.getElementById(\"classmin\").value = f1;\r\n");
      out.write("	        document.getElementById(\"classmax\").value = f2;\r\n");
      out.write("	        document.getElementById(\"classlevel\").value = selectedDifficulty;\r\n");
      out.write("	        document.getElementById(\"classprice\").value = g1;\r\n");
      out.write("	        document.getElementById(\"classstatus\").value = checkedItems.join(',');\r\n");
      out.write("	        document.addClassFrm.submit();\r\n");
      out.write("	   \r\n");
      out.write("	            \r\n");
      out.write("	        }	\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
