/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-03 02:17:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.onedaybaking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import onedaybaking.*;

public final class additem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("onedaybaking");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write('\r');
      out.write('\n');

	String id = (String)session.getAttribute("idKey");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<title>강의 등록</title>\r\n");
      out.write("	<link href=\"yeounsu.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<style>\r\n");
      out.write("		.step-section {\r\n");
      out.write("			display: none;\r\n");
      out.write("		}\r\n");
      out.write("		.step-section.active {\r\n");
      out.write("			display: block;\r\n");
      out.write("		}\r\n");
      out.write("		.detailcontainer {\r\n");
      out.write("			display: grid;\r\n");
      out.write("			grid-template-columns: repeat(2, 1fr); \r\n");
      out.write("			grid-gap: 10px; \r\n");
      out.write("			border: 1px solid #ccc;\r\n");
      out.write("			width: 700px;\r\n");
      out.write("			left: 100px;'\r\n");
      out.write("			border-color: #E7DBCC; \r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("		}\r\n");
      out.write("		.detailitem {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			margin-top: 15px;\r\n");
      out.write("			margin-bottom: 15px;\r\n");
      out.write("		}\r\n");
      out.write("		.button-container2 {\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("		}\r\n");
      out.write("		.custom-button {\r\n");
      out.write("			padding: 10px 70px;\r\n");
      out.write("			display: inline-block;\r\n");
      out.write("			margin: 0 auto;\r\n");
      out.write("			background-color: #884A01; \r\n");
      out.write("			color: white;\r\n");
      out.write("			border: 1px solid #884A01;\r\n");
      out.write("			border-radius: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		#pcate1{\r\n");
      out.write("	width:45%;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pcate2{\r\n");
      out.write("	width:45%;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write(" #pcate3{\r\n");
      out.write("	width:45%;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    }\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"button-container\">\r\n");
      out.write("            <button id=\"btnPanel1\" class=\"as active\" onclick=\"showPanel('panel1', 'btnPanel1')\">제품 소개</button>\r\n");
      out.write("            <button id=\"btnPanel2\" class=\"as\" onclick=\"showPanel('panel2', 'btnPanel2')\">상세 설명</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"panel1\" class=\"panel-container active\">\r\n");
      out.write("			<div id=\"step1\" class=\"step-section active\">\r\n");
      out.write("    			<form id=\"step1Form\" onsubmit=\"return false;\">\r\n");
      out.write("    				<label for=\"title\" style=\"font-weight: bold; font-size: 14px;\">제품 소개</label><br><br>\r\n");
      out.write("					<label id=\"notice\" for=\"notice\" style=\"font-size: 14px\">제품의 이름과 카테고리를 등록해주세요.</label><br><br>\r\n");
      out.write("					<label for=\"selectcate\">카테고리</label> <br>\r\n");
      out.write("<select id= \"pcate1\" onchange=\"categoryChange(this)\">\r\n");
      out.write("         <option>카테고리를 선택해주세요.</option>\r\n");
      out.write("         <option value=\"제과\">제과</option>\r\n");
      out.write("         <option value=\"제빵\">제빵</option>\r\n");
      out.write("         <option value=\"커피\">커피</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      \r\n");
      out.write("      <select id=\"pcate2\">\r\n");
      out.write("         <option>원하는 세부사항을 선택해주세요.</option>\r\n");
      out.write("      </select>\r\n");
      out.write("\r\n");
      out.write("					<br><br><br><br>\r\n");
      out.write("					<label for=\"productnames\">상품 명</label>\r\n");
      out.write("					<label id=\"must\">(필수)</label><br>\r\n");
      out.write("					<input type=\"text\" id=\"productnames\" name=\"typingname\" placeholder=\"제품 명을 입력하세요\" style=\"color: gray; width: 100%\"><br><br><br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<label for=\"productprice\">제품가격</label>\r\n");
      out.write("					<label id=\"must\">(필수)</label><br>\r\n");
      out.write("					<input type=\"text\" id=\"productprice\" name=\"typingname\" placeholder=\"제품가격을 입력하세요\" style=\"color: gray; width: 100%\"><br><br><br>\r\n");
      out.write("					<label for=\"producttitleimg\">대표 이미지</label>\r\n");
      out.write("					<label id=\"must\">(필수)</label> <br>\r\n");
      out.write("\r\n");
      out.write("					<div id=\"image-upload-container\" style=\"position: relative; display: inline-block; width: 50%\">\r\n");
      out.write("					    <div id=\"pimage-frame\" style=\"width: 100%; height: 200px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("					     	<img id=\"puploaded-image\" src=\"photoadd.png\" style=\"max-width: 10%; max-height: 10%; \" ><br>\r\n");
      out.write("					        클릭하여 이미지를 업로드하세요\r\n");
      out.write("					    </div >\r\n");
      out.write("					    <input type=\"file\" id=\"pimage-upload\" style=\"position: absolute; width: 100%; height: 100%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div style=\"position: absolute; display: inline-block;\">\r\n");
      out.write("						<div id=\"image-upload-container2\" style=\"position: absolute; display: inline-block;\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<div id=\"pimage-frame2\" style=\"font-size:9px; width: 150px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("									<img id=\"puploaded-image2\" src=\"photoadd.png\" style=\"max-width: 20%; max-height: 20%; \" ><br>\r\n");
      out.write("									클릭하여 이미지를 업로드하세요\r\n");
      out.write("								</div>\r\n");
      out.write("								<input type=\"file\" id=\"pimage-upload2\" style=\"position: absolute; width: 100%; height: 50%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("								<div id=\"pimage-frame3\" style=\"font-size:9px; width: 150px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("									<img id=\"puploaded-image3\" src=\"photoadd.png\" style=\"max-width: 20%; max-height: 20%; \" ><br>\r\n");
      out.write("									클릭하여 이미지를 업로드하세요\r\n");
      out.write("								</div>\r\n");
      out.write("								<input type=\"file\" id=\"pimage-upload3\" style=\"position: absolute; width: 100%; height: 50%; top: 152; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"image-upload-container2\" style=\"position: absolute; display: inline-block;\">\r\n");
      out.write("							<div style=\"position: absolute; left: 151px;\">\r\n");
      out.write("    							<div id=\"pimage-frame4\" style=\" font-size:9px; width: 150px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("     								<img id=\"puploaded-image4\" src=\"photoadd.png\" style=\"max-width: 20%; max-height: 20%; \" ><br>\r\n");
      out.write("									클릭하여 이미지를 업로드하세요\r\n");
      out.write("								</div>\r\n");
      out.write("								<input type=\"file\" id=\"pimage-upload4\" style=\"position: absolute; width: 100%; height: 50%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("								<div id=\"pimage-frame5\" style=\" font-size:9px; width: 150px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("									<img id=\"puploaded-image5\" src=\"photoadd.png\" style=\"max-width: 20%; max-height: 20%; \" ><br>\r\n");
      out.write("									클릭하여 이미지를 업로드하세요\r\n");
      out.write("								</div>\r\n");
      out.write("								<input type=\"file\" id=\"pimage-upload5\" style=\"position: absolute; width: 100%; height: 50%; top: 152; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<script>\r\n");
      out.write("					    document.getElementById('pimage-frame').addEventListener('click', function() {\r\n");
      out.write("					        document.getElementById('pimage-upload').click();        \r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('pimage-frame2').addEventListener('click', function() {\r\n");
      out.write("					        document.getElementById('pimage-upload2').click();\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('pimage-frame3').addEventListener('click', function() {\r\n");
      out.write("					        document.getElementById('pimage-upload3').click();\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('pimage-frame4').addEventListener('click', function() {\r\n");
      out.write("					        document.getElementById('pimage-upload4').click();\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('pimage-frame5').addEventListener('click', function() {\r\n");
      out.write("					        document.getElementById('pimage-upload5').click();\r\n");
      out.write("					    });\r\n");
      out.write("					\r\n");
      out.write("					    document.getElementById('pimage-upload').addEventListener('change', function() {\r\n");
      out.write("					        var file = this.files[0];\r\n");
      out.write("					        if (file) {\r\n");
      out.write("					            var reader = new FileReader();\r\n");
      out.write("					            reader.onload = function(e) {\r\n");
      out.write("					                document.getElementById('pimage-frame').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("					            };\r\n");
      out.write("					            reader.readAsDataURL(file);\r\n");
      out.write("					        }\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('pimage-upload2').addEventListener('change', function() {\r\n");
      out.write("					        var file = this.files[0];\r\n");
      out.write("					        if (file) {\r\n");
      out.write("					            var reader = new FileReader();\r\n");
      out.write("					            reader.onload = function(e) {\r\n");
      out.write("					                document.getElementById('pimage-frame2').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("					            };\r\n");
      out.write("					            reader.readAsDataURL(file);\r\n");
      out.write("					        }\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('pimage-upload3').addEventListener('change', function() {\r\n");
      out.write("					        var file = this.files[0];\r\n");
      out.write("					        if (file) {\r\n");
      out.write("					            var reader = new FileReader();\r\n");
      out.write("					            reader.onload = function(e) {\r\n");
      out.write("					                document.getElementById('pimage-frame3').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("					            };\r\n");
      out.write("					            reader.readAsDataURL(file);\r\n");
      out.write("					        }\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('pimage-upload4').addEventListener('change', function() {\r\n");
      out.write("					        var file = this.files[0];\r\n");
      out.write("					        if (file) {\r\n");
      out.write("					            var reader = new FileReader();\r\n");
      out.write("					            reader.onload = function(e) {\r\n");
      out.write("					                document.getElementById('pimage-frame4').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("					            };\r\n");
      out.write("					            reader.readAsDataURL(file);\r\n");
      out.write("					        }\r\n");
      out.write("					    });\r\n");
      out.write("					    document.getElementById('pimage-upload5').addEventListener('change', function() {\r\n");
      out.write("					        var file = this.files[0];\r\n");
      out.write("					        if (file) {\r\n");
      out.write("					            var reader = new FileReader();\r\n");
      out.write("					            reader.onload = function(e) {\r\n");
      out.write("					                document.getElementById('pimage-frame5').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("					            };\r\n");
      out.write("					            reader.readAsDataURL(file);\r\n");
      out.write("					        }\r\n");
      out.write("					    });\r\n");
      out.write("					</script>\r\n");
      out.write("					<br><br><br>\r\n");
      out.write("					<div class=\"optionlabel\">\r\n");
      out.write("					<div style=\"float: left; width:50%\">\r\n");
      out.write("					<label for=\"option\" >메인옵션</label>\r\n");
      out.write("					<label id=\"must\">(최소 1개 이상 작성)</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"float: right; width:50%\">\r\n");
      out.write("	<label for=\"option\" style=\"left: 50px\">부가옵션  (선택)</label><br>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"mainoption\">\r\n");
      out.write("    <div style=\"float: left; width: 50%;\">\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption1\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption2\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption3\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption4\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption5\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("    	<input type=\"text\" id=\"pmainoption6\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption7\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption8\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption9\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption10\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br><br><br><br>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"float: right; width: 50%;\">\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption11\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption12\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption13\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption14\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption15\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption16\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption17\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption18\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption19\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"pmainoption20\" name=\"mainoption[]\" placeholder=\"제품 옵션을 선택하세요.\" style=\"color: gray; width: 98%\"><br><br><br><br>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("			        <div class=\"button-container2\">\r\n");
      out.write("			        	<button class=\"custom-button\" onclick=\"nextStep(1)\">다음</button>\r\n");
      out.write("	        		</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		</div><!-- panel1 div -->\r\n");
      out.write("		\r\n");
      out.write("        <!-- 강사 등록하기 패널에 해당 jsp 파일 추가한 것. 이후 수정 필요 -->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("		<div id=\"panel2\" class=\"panel-container\">\r\n");
      out.write("		<div class=\"optionlabel\">\r\n");
      out.write("					<div style=\"float: left; width:50%\">\r\n");
      out.write("					<label for=\"option\" >식품유형</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"float: right; width:50%\">\r\n");
      out.write("	<label for=\"option\" style=\"left: 50px\">생산지</label>\r\n");
      out.write("	<label id=\"must\">(필수)</label>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("		<div class=\"pdail\">\r\n");
      out.write("		<div>\r\n");
      out.write("		<input type=\"text\" id=\"ptext\" style =\"float: left; width: 48%; \" disabled=\"disabled\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div >\r\n");
      out.write("		<input type=\"text\" id=\"paddress\"  placeholder=\"주소를 입력하세요.\"  style =\"float: right; width: 48%;\">\r\n");
      out.write("		</div>\r\n");
      out.write("		</div> <br><br><br><br><br>\r\n");
      out.write("		<div class=\"optionlabel\">\r\n");
      out.write("					<div style=\"float: left; width:50%\">\r\n");
      out.write("					<label for=\"option\" >제품 소비기한</label>\r\n");
      out.write("						<label id=\"must\">(필수)</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"float: right; width:50%\">\r\n");
      out.write("	<label for=\"option\" style=\"left: 50px\">보관방법</label>\r\n");
      out.write("	<label id=\"must\">(필수)</label>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("		<div class=\"pdail2\">\r\n");
      out.write("		<div>\r\n");
      out.write("		<input type=\"text\" id=\"pday\"  placeholder=\"소비기한을 작성해 주세요 ( - 일)\"  style =\"float: left; width: 48%;\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div >\r\n");
      out.write("			<select name=\"cate2\" id=\"pcate3\" style=\"float: right; width: 48%; margin-top: 8px;\">\r\n");
      out.write("					    <option value=\"냉장 보관해야해요.\">냉장 보관해야해요.</option>\r\n");
      out.write("					    <option value=\"냉동 보관해야해요.\">냉동 보관해야해요.</option>\r\n");
      out.write("					    <option value=\"실온 보관해야해요.\">실온 보관해야해요.</option>\r\n");
      out.write("					    <option value=\"직사광선을 피해서 보관해야해요.\">직사광선을 피해서 보관해야해요.</option>\r\n");
      out.write("					    <option value=\"option4\" selected=\"selected\">보관 방법을 선택하세요.</option>\r\n");
      out.write("					</select>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br><br>\r\n");
      out.write("		<br><br><br>\r\n");
      out.write("			<label for=\"title\" style=\"font-weight: bold; font-size: 14px;\">상세 설명</label><br>\r\n");
      out.write("			<br>\r\n");
      out.write("			<label id=\"notice\" for=\"notice\" style=\"font-size: 14px\">제품의 이름과 카테고리를 등록해주세요.</label><br>\r\n");
      out.write("			<br><br>\r\n");
      out.write("			\r\n");
      out.write("					<div id=\"image-upload-container3\" style=\"position: relative; display: inline-block; left: 60px;\"> <br>\r\n");
      out.write("						<div id=\"pimage-frame6\" style=\"width: 500px; height: 350px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("							<img id=\"uploaded-image6\" src=\"photoadd.png\" style=\"max-width: 10%; max-height: 10%; \" >\r\n");
      out.write("							<br>클릭하여 이미지를 업로드하세요\r\n");
      out.write("						</div>\r\n");
      out.write("						<input type=\"file\" id=\"pimage-upload6\" style=\"position: absolute; width: 100%; height: 100%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("					</div>\r\n");
      out.write("					<script>\r\n");
      out.write("						document.getElementById('pimage-frame6').addEventListener('click', function() {\r\n");
      out.write("						        document.getElementById('pimage-upload6').click();        \r\n");
      out.write("						    });\r\n");
      out.write("						    \r\n");
      out.write("						document.getElementById('pimage-upload6').addEventListener('change', function() {\r\n");
      out.write("						    var file = this.files[0];\r\n");
      out.write("						    if (file) {\r\n");
      out.write("						        var reader = new FileReader();\r\n");
      out.write("						        reader.onload = function(e) {\r\n");
      out.write("						            document.getElementById('pimage-frame6').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("						        };\r\n");
      out.write("						        reader.readAsDataURL(file);\r\n");
      out.write("						    }\r\n");
      out.write("						});\r\n");
      out.write("					</script>\r\n");
      out.write("					\r\n");
      out.write("     		<br><br><br>\r\n");
      out.write("			<div class=\"button-container2\">\r\n");
      out.write("				<form name=\"addItemFrm\" method=\"post\" action=\"addItem\" enctype=\"multipart/form-data\">\r\n");
      out.write("					<input type=\"hidden\" id=\"categorygroup\" name=\"categorygroup\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"categoryname\" name=\"categoryname\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemname\" name=\"itemname\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemprice\" name=\"itemprice\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemoption1\" name=\"itemoption1\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemoption2\" name=\"itemoption2\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemoption3\" name=\"itemoption3\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemoption4\" name=\"itemoption4\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemoption5\" name=\"itemoption5\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemoption6\" name=\"itemoption6\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemoption7\" name=\"itemoption7\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemoption8\" name=\"itemoption8\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemoption9\" name =\"itemoption9\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemoption10\" name =\"itemoption10\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemsoption1\" name =\"itemsoption1\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemsoption2\" name =\"itemsoption2\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemsoption3\" name =\"itemsoption3\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemsoption4\" name =\"itemsoption4\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemsoption5\" name =\"itemsoption5\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemsoption6\" name =\"itemsoption6\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemsoption7\" name =\"itemsoption7\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemsoption8\" name =\"itemsoption8\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemsoption9\" name =\"itemsoption9\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemsoption10\" name =\"itemsoption10\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemlocation\" name =\"itemlocation\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemperiod\" name =\"itemperiod\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemdate\" name =\"itemdate\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemimg\" name =\"itemimg\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemimg1\" name =\"itemimg1\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemimg2\" name =\"itemimg2\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemimg3\" name =\"itemimg3\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemimg4\" name =\"itemimg4\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"itemcontent\" name =\"itemcontent\" value=\"\">\r\n");
      out.write("					<input type=\"hidden\" id=\"ids\" name=\"ids\" value=\"");
      out.print(id);
      out.write("\">\r\n");
      out.write("					<input class=\"custom-button\" type=\"button\" value=\"저장하기\" onclick=\"test()\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    function categoryChange(e) {\r\n");
      out.write("        var pcate2_a = [\"케이크\", \"파이\", \"마카롱\", \"쿠키\",\"머핀\",\"버터 바\",\"팬케이크\",\"와플\",\"기타\"];\r\n");
      out.write("        var pcate2_b = [\"크로와상\", \"베이글\", \"식빵\", \"바게트\",\"호밀빵\",\"호떡\",\"롤케이크\",\"기타\"];\r\n");
      out.write("        var pcate2_c = [\"에스프레소\", \"아메리카노\", \"카페라떼\", \"카푸치노\", \"모카\",\"아이스 커피\",\"라떼\",\"마끼야또\",\"콜드 브루\",\"더치 커피\",\"기타\"];\r\n");
      out.write("        var pcate2_d = document.getElementById(\"pcate2\");\r\n");
      out.write("\r\n");
      out.write("        var target = pcate2_d;\r\n");
      out.write("\r\n");
      out.write("        if(e.value == \"제과\") var d = pcate2_a;\r\n");
      out.write("        else if(e.value == \"제빵\") var d = pcate2_b;\r\n");
      out.write("        else if(e.value == \"커피\") var d = pcate2_c;\r\n");
      out.write("\r\n");
      out.write("        target.options.length = 0;\r\n");
      out.write("\r\n");
      out.write("        for (var x in d) { \r\n");
      out.write("           var opt = document.createElement(\"option\");\r\n");
      out.write("           opt.value = d[x];\r\n");
      out.write("           opt.innerHTML = d[x];\r\n");
      out.write("           target.appendChild(opt);\r\n");
      out.write("        } \r\n");
      out.write("    }\r\n");
      out.write("		function showPanel(panelId, buttonId) {\r\n");
      out.write("			var panels = document.querySelectorAll('.panel-container');\r\n");
      out.write("			panels.forEach(function(panel) {\r\n");
      out.write("			    panel.classList.remove('active');\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			var buttons = document.querySelectorAll('.button-container button');\r\n");
      out.write("			buttons.forEach(function(button) {\r\n");
      out.write("			    button.classList.remove('active');\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			var currentPanel = document.getElementById(panelId);\r\n");
      out.write("			currentPanel.classList.add('active');\r\n");
      out.write("			\r\n");
      out.write("			var currentButton = document.getElementById(buttonId);\r\n");
      out.write("			currentButton.classList.add('active');\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function nextStep(currentStep) {\r\n");
      out.write("			if (currentStep >= 1) {\r\n");
      out.write("\r\n");
      out.write("				document.getElementById('ptext').value = document.getElementById('pcate2').value;\r\n");
      out.write("				\r\n");
      out.write("				showPanel('panel2', 'btnPanel2');\r\n");
      out.write("				currentStep--;\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			document.getElementById('step' + currentStep).classList.remove('active');\r\n");
      out.write("			document.getElementById('step' + (currentStep + 1)).classList.add('active');\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	    \r\n");
      out.write("		function previousStep(currentStep) {\r\n");
      out.write("			document.getElementById('step' + currentStep).classList.remove('active');\r\n");
      out.write("			document.getElementById('step' + (currentStep - 1)).classList.add('active');\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		function test() {\r\n");
      out.write("	        var a1 = document.getElementById(\"pcate1\").value;\r\n");
      out.write("	        var b1 = document.getElementById(\"pcate2\").value;\r\n");
      out.write("	        var c1 = document.getElementById(\"productnames\").value;\r\n");
      out.write("	        var d1 = document.getElementById(\"productprice\").value;\r\n");
      out.write("	        var imageFile = document.getElementById(\"pimage-upload\").files[0];\r\n");
      out.write("	        var imageFile2 = document.getElementById(\"pimage-upload2\").files[0];\r\n");
      out.write("	        var imageFile3 = document.getElementById(\"pimage-upload3\").files[0];\r\n");
      out.write("	        var imageFile4 = document.getElementById(\"pimage-upload4\").files[0];\r\n");
      out.write("	        var imageFile5 = document.getElementById(\"pimage-upload5\").files[0];\r\n");
      out.write("	        var imageFile6 = document.getElementById(\"pimage-upload6\").files[0];\r\n");
      out.write("	        \r\n");
      out.write("	        var o1 = document.getElementById(\"pmainoption1\").value;\r\n");
      out.write("	        var o2 = document.getElementById(\"pmainoption2\").value;\r\n");
      out.write("	        var o3 = document.getElementById(\"pmainoption3\").value;\r\n");
      out.write("	        var o4 = document.getElementById(\"pmainoption4\").value;\r\n");
      out.write("	        var o5 = document.getElementById(\"pmainoption5\").value;\r\n");
      out.write("	        var o6 = document.getElementById(\"pmainoption6\").value;\r	        var o7 = document.getElementById(\"pmainoption7\").value;\r\n");
      out.write("	        var o8 = document.getElementById(\"pmainoption8\").value;\r\n");
      out.write("	        var o9 = document.getElementById(\"pmainoption9\").value;\r\n");
      out.write("	        var o10 = document.getElementById(\"pmainoption10\").value;\r\n");
      out.write("	        var o11 = document.getElementById(\"pmainoption11\").value;\r\n");
      out.write("	        var o12 = document.getElementById(\"pmainoption12\").value;\r\n");
      out.write("	        var o13 = document.getElementById(\"pmainoption13\").value;\r\n");
      out.write("	        var o14 = document.getElementById(\"pmainoption14\").value;\r\n");
      out.write("	        var o15 = document.getElementById(\"pmainoption15\").value;\r\n");
      out.write("	        var o16 = document.getElementById(\"pmainoption16\").value;\r\n");
      out.write("	        var o17 = document.getElementById(\"pmainoption17\").value;\r\n");
      out.write("	        var o18 = document.getElementById(\"pmainoption18\").value;\r\n");
      out.write("	        var o19 = document.getElementById(\"pmainoption19\").value;\r\n");
      out.write("	        var o20 = document.getElementById(\"pmainoption20\").value;\r\n");
      out.write("	        var ppaddress = document.getElementById(\"paddress\").value; \r	        var ppday = document.getElementById(\"pday\").value; \r\n");
      out.write("	        var ppcate = document.getElementById(\"pcate3\").value;\r\n");
      out.write("	     \r\n");
      out.write("\r\n");
      out.write("	        \r\n");
      out.write("	        if (imageFile != null) {\r\n");
      out.write("		        var imageName = imageFile.name;\r\n");
      out.write("		        var reader = new FileReader();\r\n");
      out.write("		        reader.onload = function(e) {\r\n");
      out.write("					reader.readAsDataURL(imageFile);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"itemimg\").value = imageName;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile2 != null) {\r\n");
      out.write("		        var imageName2 = imageFile2.name;\r\n");
      out.write("		        var reader2 = new FileReader();\r\n");
      out.write("		        reader2.onload = function(e) {\r\n");
      out.write("					reader2.readAsDataURL(imageFile2);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"itemimg1\").value = imageName2;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile3 != null) {\r\n");
      out.write("		        var imageName3 = imageFile3.name;\r\n");
      out.write("		        var reader3 = new FileReader();\r\n");
      out.write("		        reader3.onload = function(e) {\r\n");
      out.write("					reader3.readAsDataURL(imageFile2);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"itemimg2\").value = imageName3;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile4 != null) {\r\n");
      out.write("		        var imageName4 = imageFile4.name;\r\n");
      out.write("		        var reader4 = new FileReader();\r\n");
      out.write("		        reader4.onload = function(e) {\r\n");
      out.write("					reader4.readAsDataURL(imageFile4);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"itemimg3\").value = imageName4;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile5 != null) {\r\n");
      out.write("		        var imageName5 = imageFile5.name;\r\n");
      out.write("		        var reader5 = new FileReader();\r\n");
      out.write("		        reader5.onload = function(e) {\r\n");
      out.write("					reader5.readAsDataURL(imageFile5);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"itemimg4\").value = imageName5;\r\n");
      out.write("	        }\r\n");
      out.write("	        if (imageFile6 != null) {\r\n");
      out.write("		        var imageName6 = imageFile6.name;\r\n");
      out.write("		        var reader6 = new FileReader();\r\n");
      out.write("		        reader5.onload = function(e) {\r\n");
      out.write("					reader6.readAsDataURL(imageFile6);\r\n");
      out.write("	        	}\r\n");
      out.write("		        document.getElementById(\"itemcontent\").value = imageName6;\r\n");
      out.write("	        }\r\n");
      out.write("\r\n");
      out.write("	       \r\n");
      out.write("	        document.getElementById(\"categorygroup\").value = a1;\r\n");
      out.write("	        document.getElementById(\"categoryname\").value = b1;\r\n");
      out.write("	        document.getElementById(\"itemname\").value = c1;\r\n");
      out.write("	        document.getElementById(\"itemprice\").value = d1;\r\n");
      out.write("	        document.getElementById(\"itemoption1\").value = o1;\r\n");
      out.write("	        document.getElementById(\"itemoption2\").value = o2;\r\n");
      out.write("	        document.getElementById(\"itemoption3\").value = o3;\r\n");
      out.write("	        document.getElementById(\"itemoption4\").value = o4;\r\n");
      out.write("	        document.getElementById(\"itemoption5\").value = o5;\r\n");
      out.write("	        document.getElementById(\"itemoption6\").value = o6;\r\n");
      out.write("	        document.getElementById(\"itemoption7\").value = o7;\r\n");
      out.write("	        document.getElementById(\"itemoption8\").value = o8;\r\n");
      out.write("	        document.getElementById(\"itemoption9\").value = o9;\r\n");
      out.write("	        document.getElementById(\"itemoption10\").value = o10;\r\n");
      out.write("	        document.getElementById(\"itemsoption1\").value = o11;\r\n");
      out.write("	        document.getElementById(\"itemsoption2\").value = o12;\r\n");
      out.write("	        document.getElementById(\"itemsoption3\").value = o13;\r\n");
      out.write("	        document.getElementById(\"itemsoption4\").value = o14;\r\n");
      out.write("	        document.getElementById(\"itemsoption5\").value = o15;\r\n");
      out.write("	        document.getElementById(\"itemsoption6\").value = o16;\r\n");
      out.write("	        document.getElementById(\"itemsoption7\").value = o17;\r\n");
      out.write("	        document.getElementById(\"itemsoption8\").value = o18;\r\n");
      out.write("	        document.getElementById(\"itemsoption9\").value = o19;\r\n");
      out.write("	        document.getElementById(\"itemsoption10\").value = o20;\r\n");
      out.write("	        document.getElementById(\"itemlocation\").value = ppaddress;\r\n");
      out.write("	        document.getElementById(\"itemperiod\").value = ppday;\r\n");
      out.write("	        document.addItemFrm.submit();\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
