/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-03-26 08:49:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.onedaybacking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addClass_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/onedaybacking/panel2.jsp", Long.valueOf(1711332598113L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>강의 등로</title>\r\n");
      out.write("    <link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("      \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"button-container\">\r\n");
      out.write("            <button id=\"btnPanel1\" onclick=\"showPanel('panel1', 'btnPanel1')\">강의 등록</button>\r\n");
      out.write("            <button id=\"btnPanel2\" onclick=\"showPanel('panel2', 'btnPanel2')\">강사 등록</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"panel1\" class=\"panel-container active\">\r\n");
      out.write("           <style>\r\n");
      out.write("    /* notice 라벨에 색상 추가 */\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<form style=\"width:100%\">\r\n");
      out.write("    <label for=\"title\" style=\"font-weight: bold; font-size: 14px;\">클래스 상세 내용</label><br>\r\n");
      out.write("    <br>\r\n");
      out.write("    <label id=\"notice\" for=\"notice\" style=\"font-size: 14px\">클래스 상세 내용을 작성해주세요.</label><br>\r\n");
      out.write("    \r\n");
      out.write("  <br>	\r\n");
      out.write("   <label for=\"classname\">클래스 명</label>\r\n");
      out.write("   <label id=\"must\">(필수)</label>\r\n");
      out.write("   	<br>\r\n");
      out.write("   \r\n");
      out.write("<input type=\"text\" id=\"classname\" name=\"username\" placeholder=\"클래스 명을 입력하세요\" style=\"color: gray;\"><br><br>\r\n");
      out.write("<br>\r\n");
      out.write("<label for=\"selectcate\">카테고리</label> <br>\r\n");
      out.write("<select name=\"cate1\" id=\"cate1\">\r\n");
      out.write("    <option value=\"option1\">제과</option>\r\n");
      out.write("    <option value=\"option2\">제빵</option>\r\n");
      out.write("    <option value=\"option3\">커피</option>\r\n");
      out.write("    <option value=\"option4\" selected=\"selected\">카테고리를 선택해주세요.</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("<select name=\"cate2\" id=\"cate1\">\r\n");
      out.write("    <option value=\"option1\">제과</option>\r\n");
      out.write("    <option value=\"option2\">제빵</option>\r\n");
      out.write("    <option value=\"option3\">커피</option>\r\n");
      out.write("    <option value=\"option4\" selected=\"selected\">카테고리를 선택해주세요.</option>\r\n");
      out.write("</select>\r\n");
      out.write("<br><br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<label for=\"classtitleimg\">대표 이미지</label>\r\n");
      out.write("<label id=\"must\">(필수)</label> <br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"image-upload-container\" style=\"position: relative; display: inline-block;\">\r\n");
      out.write("    <div id=\"image-frame\" style=\"width: 300px; height: 200px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("     <img id=\"uploaded-image\" src=\"photoadd.png\" style=\"max-width: 10%; max-height: 10%; \" ><br>\r\n");
      out.write("        클릭하여 이미지를 업로드하세요\r\n");
      out.write("    </div >\r\n");
      out.write("    <input type=\"file\" id=\"image-upload\" style=\"position: absolute; width: 100%; height: 100%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"position: absolute; display: inline-block;\">\r\n");
      out.write("<div id=\"image-upload-container2\" style=\"position: absolute; display: inline-block;\">\r\n");
      out.write("<div>\r\n");
      out.write("    <div id=\"image-frame2\" style=\"font-size:9px; width: 150px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("     <img id=\"uploaded-image2\" src=\"photoadd.png\" style=\"max-width: 20%; max-height: 20%; \" ><br>\r\n");
      out.write("        클릭하여 이미지를 업로드하세요\r\n");
      out.write("    </div >\r\n");
      out.write("    <input type=\"file\" id=\"image-upload2\" style=\"position: absolute; width: 100%; height: 50%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("    <div id=\"image-frame3\" style=\"font-size:9px; width: 150px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("     <img id=\"uploaded-image3\" src=\"photoadd.png\" style=\"max-width: 20%; max-height: 20%; \" ><br>\r\n");
      out.write("        클릭하여 이미지를 업로드하세요\r\n");
      out.write("    </div >\r\n");
      out.write("    <input type=\"file\" id=\"image-upload3\" style=\"position: absolute; width: 100%; height: 50%; top: 152; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"image-upload-container2\" style=\"position: absolute; display: inline-block;\">\r\n");
      out.write("<div style=\"position: absolute; left: 151px;\">\r\n");
      out.write("    <div id=\"image-frame4\" style=\" font-size:9px; width: 150px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("     <img id=\"uploaded-image4\" src=\"photoadd.png\" style=\"max-width: 20%; max-height: 20%; \" ><br>\r\n");
      out.write("        클릭하여 이미지를 업로드하세요\r\n");
      out.write("    </div >\r\n");
      out.write("    <input type=\"file\" id=\"image-upload4\" style=\"position: absolute; width: 100%; height: 50%; top: 0; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("        <div id=\"image-frame5\" style=\" font-size:9px; width: 150px; height: 100px; border: 2px solid #ccc; cursor: pointer; position: relative;  background-color: #F2F2F2; border-radius: 5px; display: flex; flex-direction: column; justify-content: center; align-items: center;\">\r\n");
      out.write("     <img id=\"uploaded-image5\" src=\"photoadd.png\" style=\"max-width: 20%; max-height: 20%; \" ><br>\r\n");
      out.write("        클릭하여 이미지를 업로드하세요\r\n");
      out.write("    </div >\r\n");
      out.write("    <input type=\"file\" id=\"image-upload5\" style=\"position: absolute; width: 100%; height: 50%; top: 152; left: 0; opacity: 0; cursor: pointer; \">\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.getElementById('image-frame').addEventListener('click', function() {\r\n");
      out.write("        document.getElementById('image-upload').click();        \r\n");
      out.write("    });\r\n");
      out.write("    document.getElementById('image-frame2').addEventListener('click', function() {\r\n");
      out.write("        document.getElementById('image-upload2').click();\r\n");
      out.write("    });\r\n");
      out.write("    document.getElementById('image-frame3').addEventListener('click', function() {\r\n");
      out.write("        document.getElementById('image-upload3').click();\r\n");
      out.write("    });\r\n");
      out.write("    document.getElementById('image-frame4').addEventListener('click', function() {\r\n");
      out.write("        document.getElementById('image-upload4').click();\r\n");
      out.write("    });\r\n");
      out.write("    document.getElementById('image-frame5').addEventListener('click', function() {\r\n");
      out.write("        document.getElementById('image-upload5').click();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('image-upload').addEventListener('change', function() {\r\n");
      out.write("        var file = this.files[0];\r\n");
      out.write("        if (file) {\r\n");
      out.write("            var reader = new FileReader();\r\n");
      out.write("            reader.onload = function(e) {\r\n");
      out.write("                document.getElementById('image-frame').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("            };\r\n");
      out.write("            reader.readAsDataURL(file);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    document.getElementById('image-upload2').addEventListener('change', function() {\r\n");
      out.write("        var file = this.files[0];\r\n");
      out.write("        if (file) {\r\n");
      out.write("            var reader = new FileReader();\r\n");
      out.write("            reader.onload = function(e) {\r\n");
      out.write("                document.getElementById('image-frame2').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("            };\r\n");
      out.write("            reader.readAsDataURL(file);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    document.getElementById('image-upload3').addEventListener('change', function() {\r\n");
      out.write("        var file = this.files[0];\r\n");
      out.write("        if (file) {\r\n");
      out.write("            var reader = new FileReader();\r\n");
      out.write("            reader.onload = function(e) {\r\n");
      out.write("                document.getElementById('image-frame3').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("            };\r\n");
      out.write("            reader.readAsDataURL(file);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    document.getElementById('image-upload4').addEventListener('change', function() {\r\n");
      out.write("        var file = this.files[0];\r\n");
      out.write("        if (file) {\r\n");
      out.write("            var reader = new FileReader();\r\n");
      out.write("            reader.onload = function(e) {\r\n");
      out.write("                document.getElementById('image-frame4').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("            };\r\n");
      out.write("            reader.readAsDataURL(file);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    document.getElementById('image-upload5').addEventListener('change', function() {\r\n");
      out.write("        var file = this.files[0];\r\n");
      out.write("        if (file) {\r\n");
      out.write("            var reader = new FileReader();\r\n");
      out.write("            reader.onload = function(e) {\r\n");
      out.write("                document.getElementById('image-frame5').innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width: 100%; max-height: 100%;\">';\r\n");
      out.write("            };\r\n");
      out.write("            reader.readAsDataURL(file);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<label for=\"classhard\">수업 난이도</label>\r\n");
      out.write("<label id=\"must\">(필수)</label> <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div class=\"btn-group\" role=\"group\" aria-label=\"Basic radio toggle button group\">\r\n");
      out.write("  <input type=\"radio\" class=\"btn-check\"  name=\"btnradio\" id=\"btnradio1\" autocomplete=\"off\" checked>\r\n");
      out.write("  <label class=\"btn btn-outline-primary\" for=\"btnradio1\">초급</label>\r\n");
      out.write("\r\n");
      out.write("  <input type=\"radio\" class=\"btn-check\" name=\"btnradio\" id=\"btnradio2\" autocomplete=\"off\">\r\n");
      out.write("  <label class=\"btn btn-outline-primary\" for=\"btnradio2\">중급</label>\r\n");
      out.write("\r\n");
      out.write("  <input type=\"radio\" class=\"btn-check\" name=\"btnradio\" id=\"btnradio3\" autocomplete=\"off\">\r\n");
      out.write("  <label class=\"btn btn-outline-primary\" for=\"btnradio3\">고급</label>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<label for=\"classfortime\">수업 소요시간</label>\r\n");
      out.write("   <label id=\"must\">(필수)</label> <br>\r\n");
      out.write("<input type=\"text\" id=\"classname\" name=\"username\" placeholder=\"30분 단위로 적어주세요 ex) 150\" style=\"color: gray;\"><br><br>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("   <table>\r\n");
      out.write("  <tbody>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td rowspan=\"2\"><label for=\"classfortime\">수업 소요시간</label>\r\n");
      out.write("   <label id=\"must\">(필수) &nbsp; &nbsp; &nbsp;</label> </td>\r\n");
      out.write("      <td colspan=\"2\" style=\"text-align: center;\" >최소 인원</td>\r\n");
      out.write("      <td style=\"text-align: center;\">최대 인원</td>\r\n");
      out.write("      \r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td><input type=\"text\" id=\"classname\" name=\"username\" placeholder=\"명\" style=\"color: gray; text-align: right;\"></td>\r\n");
      out.write("      <td>/ &nbsp; &nbsp;&nbsp;</td>\r\n");
      out.write("      <td><input type=\"text\" id=\"classname\" name=\"username\" placeholder=\"명\" style=\"color: gray; text-align: right;\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<label for=\"classfortime\">1인 수강금액</label>\r\n");
      out.write("   <label id=\"must\">(필수)</label> <br>\r\n");
      out.write("<input type=\"text\" id=\"classname\" name=\"username\" placeholder=\"원\" style=\"color: gray;text-align: right;\"><br><br>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("<br>\r\n");
      out.write("</form>\r\n");
      out.write(" <script>\r\n");
      out.write("      \r\n");
      out.write("    </script>\r\n");
      out.write("        </div>\r\n");
      out.write("	\r\n");
      out.write("        <div id=\"panel2\" class=\"panel-container\">	\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("<form>\r\n");
      out.write("    <label for=\"username\">사용자 이름:</label>\r\n");
      out.write("    <input type=\"text\" id=\"username\" name=\"username\"><br><br>\r\n");
      out.write("    <label for=\"password\">비밀번호:</label>\r\n");
      out.write("    <input type=\"password\" id=\"password\" name=\"password\"><br><br>\r\n");
      out.write("    <input type=\"submit\" value=\"로그인\">\r\n");
      out.write("</form>");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    function showPanel(panelId, buttonId) {\r\n");
      out.write("        var panels = document.querySelectorAll('.panel-container');\r\n");
      out.write("        panels.forEach(function(panel) {\r\n");
      out.write("            panel.classList.remove('active');\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        var buttons = document.querySelectorAll('.button-container button');\r\n");
      out.write("        buttons.forEach(function(button) {\r\n");
      out.write("            button.classList.remove('active');\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        var currentPanel = document.getElementById(panelId);\r\n");
      out.write("        currentPanel.classList.add('active');\r\n");
      out.write("\r\n");
      out.write("        var currentButton = document.getElementById(buttonId);\r\n");
      out.write("        currentButton.classList.add('active');\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"button-group\">\r\n");
      out.write("            <button>\r\n");
      out.write("            <a  href=\"panel3.jsp\">이전</a></button>\r\n");
      out.write("            <button type=\"button\" onclick=\"javascript:location.href='panel3.jsp'\">다음</button>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
