/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-02 02:28:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.onedaybacking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      onedaybaking.MemberMgr mgr = null;
      mgr = (onedaybaking.MemberMgr) _jspx_page_context.getAttribute("mgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mgr == null){
        mgr = new onedaybaking.MemberMgr();
        _jspx_page_context.setAttribute("mgr", mgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body align=\"center\">\r\n");
      out.write("<img src=\"logo/logo.png\" height=\"150\">\r\n");
      out.write("<h1>회원가입<hr><br></h1>\r\n");
      out.write("<form name=\"frm\" method=\"post\" action=\"signinProc.jsp\">\r\n");
      out.write("<table align=\"center\" class=\"table-spacing\">\r\n");
      out.write("	<tr align=\"center\" class=\"id\">\r\n");
      out.write("		<td>아이디<font color=\"red\">*</font></td>\r\n");
      out.write("		\r\n");
      out.write("		<td><img src=\"logo/email.png\" width=\"25\" height=\"20\"></td>\r\n");
      out.write("		<td width=\"50\">\r\n");
      out.write("			<!-- // todo. Key Event 추가 -->\r\n");
      out.write("			<input id=\"member_id\" name=\"memberId\" class=\"text\" size=\"45\" placeholder=\"아이디를 입력하세요\" value=\"\">\r\n");
      out.write("			<input type=\"hidden\" id=\"check_duplication\" value=\"N\">\r\n");
      out.write("		</td>\r\n");
      out.write("		<td><input type=\"button\" value=\"중복확인\" onClick=\"idCheck(this.form.memberId.value)\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr align=\"center\">\r\n");
      out.write("		<td colspan=\"3\" class=\"id-text\"><font color=\"gray\">영어소문자와 숫자를 이용하여 4~12자리의 아이디를 입력해주세요</font></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr align=\"center\"  class=\"password\">\r\n");
      out.write("		<td>비밀번호<font color=\"red\">*</font></td>\r\n");
      out.write("		<td><img src=\"logo/padlock.png\" width=\"25\" height=\"20\"></td>\r\n");
      out.write("		<td width=\"50\"><input type=\"password\" id=\"password\" class=\"text\" name=\"memberPwd\" size=\"45\" placeholder=\"비밀번호를 입력하세요\" value=\"\"></td>\r\n");
      out.write("		<td><img src=\"logo/hide.png\" width=\"25\" height=\"20\" id=\"togglePwd\" ></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr align=\"center\">\r\n");
      out.write("		<td colspan=\"3\" class=\"id-text\"><font color=\"gray\">4자리 이상의 비밀번호를 입력해주세요</font></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr align=\"center\">\r\n");
      out.write("		<td>비밀번호 확인<font color=\"red\">*</font></td>\r\n");
      out.write("		<td><img src=\"logo/padlock.png\" width=\"25\" height=\"20\"></td>\r\n");
      out.write("		<td width=\"50\"><input type=\"password\" id=\"repassword\" class=\"text\" name=\"repassword\" size=\"45\" placeholder=\"비밀번호 확인\" value=\"\"></td>\r\n");
      out.write("		<td><img src=\"logo/hide.png\" width=\"25\" height=\"20\" id=\"retogglePwd\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr align=\"center\">\r\n");
      out.write("		<td>이름<font color=\"red\">*</font></td>\r\n");
      out.write("		<td><img src=\"logo/member.png\" width=\"25\" height=\"20\"></td>\r\n");
      out.write("		<td width=\"50\"><input name=\"memberName\"  class=\"text\" size=\"45\" placeholder=\"이름을 입력하세요\" value=\"\" ></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr align=\"center\">\r\n");
      out.write("		<td>닉네임<font color=\"red\">*</font></td>\r\n");
      out.write("		<td><img src=\"logo/member.png\" width=\"25\" height=\"20\"></td>\r\n");
      out.write("		<td width=\"50\"><input class=\"text\" name=\"memberNick\" class=\"text\" size=\"45\" placeholder=\"닉네임을 입력하세요\" value=\"\" ></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr align=\"center\">\r\n");
      out.write("		<td>전화번호<font color=\"red\">*</font></td>\r\n");
      out.write("		<td><img src=\"logo/phone.png\" width=\"25\" height=\"20\"></td>\r\n");
      out.write("		<td width=\"50\"><input name=\"memberPhone\" class=\"text\" size=\"45\" placeholder=\"-를 제외한 번호만 입력하세요\" value=\"\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr align=\"center\">\r\n");
      out.write("		<td>생년월일<font color=\"red\">*</font></td>\r\n");
      out.write("		<td><img src=\"logo/date.png\" width=\"25\" height=\"20\"></td>\r\n");
      out.write("		<td width=\"50\"><input name=\"memberBirth\" class=\"text\" size=\"45\" placeholder=\"8자리 입력하세요(ex. 20001016)\" value=\"\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr align=\"center\">\r\n");
      out.write("		<td>성별<font color=\"red\">*</font></td>\r\n");
      out.write("		<td width=\"50\" colspan=\"2\" class=\"gender\">\r\n");
      out.write(" 		<input type=\"radio\" name=\"memberSex\" value=\"0\" checked>남\r\n");
      out.write("		<input type=\"radio\" name=\"memberSex\" value=\"1\">여</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"4\" align=\"center\" class=\"agree\" >\r\n");
      out.write("			<input type=\"checkbox\"  name=\"allCh\" onclick=\"allChk()\"checked>모두 동의합니다.<br><br>\r\n");
      out.write("			<input type=\"checkbox\"  name=\"fch\" onclick=\"chk()\"checked>[필수]만 14세 이상입니다.<br><br>\r\n");
      out.write("			<input type=\"checkbox\"  name=\"sch\" onclick=\"chk()\"checked>[필수]이용약관 동의<br><br>\r\n");
      out.write("			<input type=\"checkbox\"  name=\"tch\" onclick=\"chk()\"checked>[선택] 개인정보 수집 및 이용 동의</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"4\"><br><br></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("</table>\r\n");
      out.write("<input type=\"button\" class=\"button\" value=\"회원가입\" onclick=\"inputCheck()\"><br><br><br><br>\r\n");
      out.write("<div style=\"font-size:20px\">아이디가 있으신가요? <b><a href=\"login.jsp\">로그인</a></b>하기 <br><br><br><br><br><br><br><br> </div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
