/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-02 02:40:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.onedaybacking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import onedaybaking.MemberBean;
import onedaybaking.MemberAddressBean;

public final class myinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("onedaybaking.MemberBean");
    _jspx_imports_classes.add("onedaybaking.MemberAddressBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("																																																				\r\n");
      out.write("\r\n");
      out.write("\r\n");
      onedaybaking.MemberMgr mgr = null;
      mgr = (onedaybaking.MemberMgr) _jspx_page_context.getAttribute("mgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mgr == null){
        mgr = new onedaybaking.MemberMgr();
        _jspx_page_context.setAttribute("mgr", mgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

	
	String memberId = (String)session.getAttribute("idKey");
	MemberBean mBean = mgr.memberList(memberId);
	MemberAddressBean maBean = mgr.AddressList(memberId);

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\">\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"myinfo_style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("<br><br><br><br><br>\r\n");
      out.write(" <div style=\"width: 55%;  margin: auto\">\r\n");
      out.write(" <div class=\"tdiv\" style=\"width: 25%; float: left;\">\r\n");
      out.write("	<table class=\"card_body\" style=\"width: 100%;\">\r\n");
      out.write("		<tr>\r\n");
      out.write("	  		<td><br></td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("		 <tr>\r\n");
      out.write("		 	 <td>\r\n");
      out.write("		 	 <img src=\"img/");
      out.print(mBean.getMemberInfoImg() );
      out.write("\" class=\"infoImg\">\r\n");
      out.write("		  	<input type=\"button\" class=\"inqButton\" value=\"문의내역\" onclick=\"location.href = 'myInquire.jsp';\">\r\n");
      out.write("	  		</td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>\r\n");
      out.write("	  		<td><br></td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>\r\n");
      out.write("	  		<td><input type=\"button\" class=\"signButton\" value=\"회원정보 수정\" onclick=\"location.href='signUpdate.jsp';\"></td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>\r\n");
      out.write("	  		<td><br></td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>\r\n");
      out.write("	  		<td>아이디 : ");
      out.print(mBean.getMemberId() );
      out.write("</td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>\r\n");
      out.write("	  		<td><br></td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>\r\n");
      out.write("	  		<td>이름 : ");
      out.print(mBean.getMemberName());
      out.write("</td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>\r\n");
      out.write("	  		<td><br></td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>\r\n");
      out.write("	  		<td>기본 배송지 : </td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>\r\n");
      out.write("	  		<td><br></td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>\r\n");
      out.write("	  		<td>\r\n");
      out.write("	 		");
if(maBean.getAddress() == null) {
      out.write("\r\n");
      out.write("	 		기본 배송지를 입력해주세요.\r\n");
      out.write("	 		");
 } else { 
      out.write("\r\n");
      out.write("	  		");
      out.print(maBean.getAddress() );
      out.write("\r\n");
      out.write("	  		");
 } 
      out.write("\r\n");
      out.write("	  		</td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>\r\n");
      out.write("	  		<td><br></td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>\r\n");
      out.write("	  		<td>\r\n");
      out.write("	 		");
if(maBean.getAddressDetail() == null) {
      out.write("\r\n");
      out.write("	 		\r\n");
      out.write("	 		");
 } else { 
      out.write("\r\n");
      out.write("	  		");
      out.print(maBean.getAddressDetail());
      out.write("\r\n");
      out.write("	  		");
 } 
      out.write("\r\n");
      out.write("	  		</td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	  	<tr>														\r\n");
      out.write("	  		<td><br><br></td>\r\n");
      out.write("	  	</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	</div>\r\n");
      out.write("<table style=\"width:5%; float:center\"></table>\r\n");
      out.write("<table  class=\"info_box\"style=\"width:70%; float: right\">\r\n");
      out.write("<tr>\r\n");
      out.write("	<td  class=\"cards\" onclick=\"location.href=''\">\r\n");
      out.write("    <p class=\"card-title\">내 상품 관리</p>\r\n");
      out.write("    <p></p>\r\n");
      out.write("    <p class=\"card-text\">자신이 등록한 상품을 확인해 보세요!</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td class=\"space\"></td>\r\n");
      out.write("	<td class=\"cards\" onclick=\"location.href='wish.jsp'\">\r\n");
      out.write("    <p class=\"card-title\">찜 목록</p>\r\n");
      out.write("    <p></p>\r\n");
      out.write("    <p class=\"card-text\">자신이 찜한 상품과 클래스를 확인해 보세요!</p>\r\n");
      out.write("    </td>\r\n");
      out.write("     <td class=\"space\"></td>\r\n");
      out.write("	<td class=\"cards\" onclick=\"location.href=''\">\r\n");
      out.write("    <p class=\"card-title\">주문 정보</p>\r\n");
      out.write("    <p></p>\r\n");
      out.write("    <p class=\"card-text\">자신이 주문한 상품을 확인해 보세요!</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td class=\"space\"></td>\r\n");
      out.write("  <tr>\r\n");
      out.write("	<td><br><br></td>\r\n");
      out.write("  </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("	<td class=\"cards\" onclick=\"location.href=''\">\r\n");
      out.write("    <p class=\"card-title\">내 클래스 관리</p>\r\n");
      out.write("    <p></p>\r\n");
      out.write("    <p class=\"card-text\">자신이 등록한 클래스를 확인해 보세요!</p>\r\n");
      out.write("	</td>\r\n");
      out.write("	<td class=\"space\"></td>\r\n");
      out.write("	<td class=\"cards\" onclick=\"location.href='coupon.jsp'\">\r\n");
      out.write("    <p class=\"card-title\">쿠폰함</p>\r\n");
      out.write("    <p></p>\r\n");
      out.write("    <p class=\"card-text\">자신이 보유하고 있는 쿠폰을 확인해 보세요!</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td class=\"space\"></td>\r\n");
      out.write("	<td class=\"cards\" onclick=\"location.href=''\">\r\n");
      out.write("    <p class=\"card-title\">클래스 정보</p>\r\n");
      out.write("    <p></p>\r\n");
      out.write("    <p class=\"card-text\">자신이 예약한 클래스를 확인해 보세요!</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td class=\"space\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("<br><br><br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
