/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-02 03:33:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.onedaybacking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import onedaybaking.ClassBean;
import onedaybaking.ItemBean;
import java.util.Vector;

public final class wish_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("onedaybaking.ItemBean");
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("onedaybaking.ClassBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- wish.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      onedaybaking.WishMgr mgr = null;
      mgr = (onedaybaking.WishMgr) _jspx_page_context.getAttribute("mgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mgr == null){
        mgr = new onedaybaking.WishMgr();
        _jspx_page_context.setAttribute("mgr", mgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

	String memberId = (String)session.getAttribute("idKey");
	int items = mgr.getWishItem(memberId);
	int classs = mgr.getWishClass(memberId);

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<link href=\"myinfo_style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("	<script type=\"text/javascript\" src=\"script.js\"></script>\r\n");
      out.write("	<link href=\"panel.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("	\r\n");
      out.write("	<style>\r\n");
      out.write("	\r\n");
      out.write("		.step-section {\r\n");
      out.write("			display: none;\r\n");
      out.write("		}\r\n");
      out.write("		.step-section.active {\r\n");
      out.write("			display: block;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("            div.card img {\r\n");
      out.write("                height: 180px;\r\n");
      out.write("                object-fit: cover;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            a {\r\n");
      out.write("                text-decoration-line: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            p {\r\n");
      out.write("                width: 95%;\r\n");
      out.write("                text-overflow: ellipsis;\r\n");
      out.write("                overflow: hidden;\r\n");
      out.write("                white-space: nowrap;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            div.as {\r\n");
      out.write("                width: 150px;\r\n");
      out.write("            }\r\n");
      out.write("	</style>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("		function showPanel(panelId, buttonId) {\r\n");
      out.write("			var panels = document.querySelectorAll('.panel-containers');\r\n");
      out.write("			panels.forEach(function(panel) {\r\n");
      out.write("				panel.classList.remove('active');\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			var buttons = document.querySelectorAll('.button-containers button');\r\n");
      out.write("			buttons.forEach(function(button) {\r\n");
      out.write("				button.classList.remove('active');\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			var currentPanel = document.getElementById(panelId);\r\n");
      out.write("			currentPanel.classList.add('active');\r\n");
      out.write("			\r\n");
      out.write("			var currentButton = document.getElementById(buttonId);\r\n");
      out.write("			currentButton.classList.add('active');\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		$(function() {\r\n");
      out.write("			$(document).ready(function() {\r\n");
      out.write("				$(\"#btn-add-item\").trigger(\"click\");\r\n");
      out.write("				$(\"#btn-add-class\").trigger(\"click\");\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			var icnt = 0, istart = 0, ccnt = 0, cstart = 0;\r\n");
      out.write("			\r\n");
      out.write("			$(\"#btn-add-item\").on(\"click\", function() {\r\n");
      out.write("				var html = \"\";\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"getWishItemList.jsp\", // AJAX 요청을 처리할 JSP 페이지 경로\r\n");
      out.write("					type: \"GET\",\r\n");
      out.write("					success: function(response) {\r\n");
      out.write("						var ivlist = JSON.parse(response); // JSON 형식의 데이터 파싱\r\n");
      out.write("						for (var i = istart; i <= ivlist.length; i++) {\r\n");
      out.write("							if (ivlist.length == i) {\r\n");
      out.write("								istart = ivlist.length;\r\n");
      out.write("								break;\r\n");
      out.write("							}\r\n");
      out.write("							\r\n");
      out.write("							if (i > istart + 5) {\r\n");
      out.write("								istart += 6;\r\n");
      out.write("								break;\r\n");
      out.write("							}\r\n");
      out.write("							\r\n");
      out.write("							icnt++;\r\n");
      out.write("							var ibean = ivlist[i];\r\n");
      out.write("							html += \"<div class='col mt-2 mb-2'>\";\r\n");
      out.write("							html += \"<a href='board_view.html?id=\" + ibean.itemkey + \"' style='text-decoration-line: none;'>\";\r\n");
      out.write("							html += \"<div class='card h-100 ' style='card-border-radius: .75rem;'>\";\r\n");
      out.write("							html += \"<img src='img/img01.jpg' class='card-img-top' alt=''>\";\r\n");
      out.write("							html += \"<div class='card-body p-2 pb-3'>\";\r\n");
      out.write("							html += \"<h5 class='card-title'><small>\" + ibean.itemname + \"</small></h5>\";\r\n");
      out.write("							html += \"<p class='card-text'><small>\" + ibean.membername + \"</small></p>\";\r\n");
      out.write("							html += \"</div>\";\r\n");
      out.write("							html += \"<div class='card-footer text-end'>\";\r\n");
      out.write("							html += \"<small class='text-body-secondary'> \" + ibean.itemprice + \"원</small>\";\r\n");
      out.write("							html += \"</div>\";\r\n");
      out.write("							html += \"</div>\";\r\n");
      out.write("							html += \"</a>\";\r\n");
      out.write("							html += \"</div>\";\r\n");
      out.write("						}\r\n");
      out.write("						$(\"div#row_item\").append(html);\r\n");
      out.write("					},\r\n");
      out.write("					error: function(xhr, status, error) {\r\n");
      out.write("						console.error(\"Error:\", error);\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\"#btn-add-class\").on(\"click\", function() {\r\n");
      out.write("				var htmls = \"\";\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"getWishClassList.jsp\", // AJAX 요청을 처리할 JSP 페이지 경로\r\n");
      out.write("					type: \"GET\",\r\n");
      out.write("					success: function(response) {\r\n");
      out.write("						var cvlist = JSON.parse(response); // JSON 형식의 데이터 파싱\r\n");
      out.write("						for (var i = cstart; i <= cvlist.length; i++) {\r\n");
      out.write("							if (cvlist.length == i) {\r\n");
      out.write("								cstart = cvlist.length;\r\n");
      out.write("								break;\r\n");
      out.write("							}\r\n");
      out.write("							\r\n");
      out.write("							if (i > cstart + 5) {\r\n");
      out.write("								cstart += 6;\r\n");
      out.write("								break;\r\n");
      out.write("							}\r\n");
      out.write("							\r\n");
      out.write("							ccnt++;\r\n");
      out.write("							var cbean = cvlist[i];\r\n");
      out.write("							htmls += \"<div class='col mt-2 mb-2'>\";\r\n");
      out.write("							htmls += \"<a href='board_view.html?id=\" + cbean.classkey + \"' style='text-decoration-line:none;'>\";\r\n");
      out.write("							htmls += \"<div class='card h-100'>\";\r\n");
      out.write("							htmls += \"<img src='img/img01.jpg' class='card-img-top' alt=''>\";\r\n");
      out.write("							htmls += \"<div class='card-body p-2 pb-3'>\";\r\n");
      out.write("							htmls += \"<h5 class='card-title'><small>\" + cbean.classname + \"</small></h5>\";\r\n");
      out.write("							htmls += \"<p class='card-text'><small>\" + cbean.membername + \"</small></p>\";\r\n");
      out.write("							htmls += \"</div>\";\r\n");
      out.write("							htmls += \"<div class='card-footer text-end'>\";\r\n");
      out.write("							htmls += \"<small class='text-body-secondary'>\" + cbean.classprice + \"원</small>\";\r\n");
      out.write("							htmls += \"</div>\";\r\n");
      out.write("							htmls += \"</div>\";\r\n");
      out.write("							htmls += \"</a>\";\r\n");
      out.write("							htmls += \"</div>\";\r\n");
      out.write("						}\r\n");
      out.write("						$(\"div#row_class\").append(htmls);\r\n");
      out.write("					},\r\n");
      out.write("					error: function(xhr, status, error) {\r\n");
      out.write("						console.error(\"Error:\", error);\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("	<div style=\"width: 55%;  margin: auto;\">\r\n");
      out.write("		<div class=\"wishTitle\">\r\n");
      out.write("			<p>위시리스트</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"containers\">\r\n");
      out.write("			<div class=\"button-containers\">\r\n");
      out.write("				<button id=\"btnPanel1\" class=\"btnPanel active\" onclick=\"showPanel('panel1', 'btnPanel1')\">상품 (");
      out.print(items );
      out.write(")</button>\r\n");
      out.write("				<button id=\"btnPanel2\" class=\"btnPanel\" onclick=\"showPanel('panel2', 'btnPanel2')\">클래스 (");
      out.print(classs );
      out.write(")</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"panel1\" class=\"panel-containers active\">\r\n");
      out.write("			");

				if (items == 0) {
			
      out.write("\r\n");
      out.write("				찜 목록이 비었습니다.\r\n");
      out.write("			");

				} else {
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		       	<div class=\"containera\">\r\n");
      out.write("					<div class=\"row row-cols-md-3\" id=\"row_item\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<button class=\"btn btn-light btn-lg w-100 mt-2\" id=\"btn-add-item\">더 보기</button>\r\n");
      out.write("				</div>	\r\n");
      out.write("			");
 }
			
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"panel2\" class=\"panel-containers\">\r\n");
      out.write("			");

				if (classs == 0) {
			
      out.write("\r\n");
      out.write("				찜 목록이 비었습니다.\r\n");
      out.write("			");

				} else {
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		       	<div class=\"containera\">\r\n");
      out.write("					<div class=\"row row-cols-md-3\" id=\"row_class\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<button class=\"btn btn-light btn-lg w-100 mt-2\" id=\"btn-add-class\">더 보기</button>\r\n");
      out.write("				</div>	\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
